MODULE BIO
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: ERROR_UNIT
  IMPLICIT NONE

  INTEGER, PARAMETER, PRIVATE :: IOMSGLEN = 66

CONTAINS

  SUBROUTINE BIO_OPEN(U, FN, ACT, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(INOUT) :: U
    CHARACTER(LEN=*), INTENT(IN) :: FN, ACT
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG
    CHARACTER(LEN=9) :: FACT
    CHARACTER(LEN=7) :: STAT

    IF (U .LT. -1) THEN
       INFO = -1
    ELSE IF (LEN_TRIM(FN) .LE. 0) THEN
       INFO = -2
    ELSE IF (LEN_TRIM(ACT) .NE. 2) THEN
       INFO = -3
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    SELECT CASE (ACT(1:1))
    CASE ('R', 'r')
       STAT = 'OLD'
       SELECT CASE (ACT(2:2))
       CASE ('O', 'o')
          FACT = 'READ'
       CASE ('W', 'w')
          FACT = 'READWRITE'
       CASE DEFAULT
          INFO = -3
       END SELECT
    CASE ('W', 'w')
       STAT = 'REPLACE'
       SELECT CASE (ACT(2:2))
       CASE ('O', 'o')
          FACT = 'WRITE'
       CASE ('R', 'r')
          FACT = 'READWRITE'
       CASE DEFAULT
          INFO = -3
       END SELECT
    CASE DEFAULT
       INFO = -3
    END SELECT
    IF (INFO .NE. 0) RETURN

    IF (U .EQ. -1) THEN
       OPEN(NEWUNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=1, FILE=TRIM(FN), STATUS=TRIM(STAT), ACTION=TRIM(FACT),&
            ACCESS='STREAM', FORM='UNFORMATTED')
    ELSE
       OPEN(UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=1, FILE=TRIM(FN), STATUS=TRIM(STAT), ACTION=TRIM(FACT),&
            ACCESS='STREAM', FORM='UNFORMATTED')
    END IF
    RETURN
1   WRITE (ERROR_UNIT,'(2A)') 'BIO_OPEN    :', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_OPEN

  SUBROUTINE BIO_CLOSE(U, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(INOUT) :: U
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    INFO = 0
    CLOSE(UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=2)
    U = -1
    RETURN
2   WRITE (ERROR_UNIT,'(2A)') 'BIO_CLOSE   :', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_CLOSE

  SUBROUTINE BIO_READ_D1(U, N, A, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: U, N
    DOUBLE PRECISION, INTENT(OUT) :: A(N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (N .LT. 0) THEN
       INFO = -2
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    READ (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=3) A
    RETURN
3   WRITE (ERROR_UNIT,'(2A)') 'BIO_READ_D1 :', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_READ_D1

  SUBROUTINE BIO_WRITE_D1(U, N, A, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: U, N
    DOUBLE PRECISION, INTENT(IN) :: A(N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (N .LT. 0) THEN
       INFO = -2
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    WRITE (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=4) A
    RETURN
4   WRITE (ERROR_UNIT,'(2A)') 'BIO_WRITE_D1:', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_WRITE_D1

  SUBROUTINE BIO_READ_D2(U, M, N, A, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: U, M, N
    DOUBLE PRECISION, INTENT(OUT) :: A(M,N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (M .LT. 0) THEN
       INFO = -2
    ELSE IF (N .LT. 0) THEN
       INFO = -3
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    READ (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=5) A
    RETURN
5   WRITE (ERROR_UNIT,'(2A)') 'BIO_READ_D2 :', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_READ_D2

  SUBROUTINE BIO_WRITE_D2(U, M, N, A, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: U, M, N
    DOUBLE PRECISION, INTENT(IN) :: A(M,N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (M .LT. 0) THEN
       INFO = -2
    ELSE IF (N .LT. 0) THEN
       INFO = -3
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    WRITE (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=6) A
    RETURN
6   WRITE (ERROR_UNIT,'(2A)') 'BIO_WRITE_D2:', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_WRITE_D2

  SUBROUTINE BIO_READ_Z2(U, M, N, A, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: U, M, N
    DOUBLE COMPLEX, INTENT(OUT) :: A(M,N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (M .LT. 0) THEN
       INFO = -2
    ELSE IF (N .LT. 0) THEN
       INFO = -3
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    READ (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=7) A
    RETURN
7   WRITE (ERROR_UNIT,'(2A)') 'BIO_READ_Z2 :', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_READ_Z2

  SUBROUTINE BIO_WRITE_Z2(U, M, N, A, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: U, M, N
    DOUBLE COMPLEX, INTENT(IN) :: A(M,N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (M .LT. 0) THEN
       INFO = -2
    ELSE IF (N .LT. 0) THEN
       INFO = -3
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    WRITE (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=8) A
    RETURN
8   WRITE (ERROR_UNIT,'(2A)') 'BIO_WRITE_Z2:', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_WRITE_Z2

#ifdef QX_WP
  SUBROUTINE BIO_READ_Q1(U, N, A, INFO)
    IMPLICIT NONE
    INTEGER, PARAMETER :: WP = QX_WP
    INTEGER, INTENT(IN) :: U, N
    REAL(KIND=WP), INTENT(OUT) :: A(N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (N .LT. 0) THEN
       INFO = -2
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    READ (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=9) A
    RETURN
9   WRITE (ERROR_UNIT,'(2A)') 'BIO_READ_Q1 :', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_READ_Q1

  SUBROUTINE BIO_WRITE_Q1(U, N, A, INFO)
    IMPLICIT NONE
    INTEGER, PARAMETER :: WP = QX_WP
    INTEGER, INTENT(IN) :: U, N
    REAL(KIND=WP), INTENT(IN) :: A(N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (N .LT. 0) THEN
       INFO = -2
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    WRITE (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=10) A
    RETURN
10  WRITE (ERROR_UNIT,'(2A)') 'BIO_WRITE_Q1:', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_WRITE_Q1
#endif

  SUBROUTINE BIO_READ_S1(U, N, A, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: U, N
    REAL, INTENT(OUT) :: A(N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (N .LT. 0) THEN
       INFO = -2
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    READ (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=11) A
    RETURN
11  WRITE (ERROR_UNIT,'(2A)') 'BIO_READ_S1 :', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_READ_S1

  SUBROUTINE BIO_WRITE_S1(U, N, A, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: U, N
    REAL, INTENT(IN) :: A(N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (N .LT. 0) THEN
       INFO = -2
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    WRITE (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=12) A
    RETURN
12  WRITE (ERROR_UNIT,'(2A)') 'BIO_WRITE_S1:', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_WRITE_S1

  SUBROUTINE BIO_READ_S2(U, M, N, A, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: U, M, N
    REAL, INTENT(OUT) :: A(M,N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (M .LT. 0) THEN
       INFO = -2
    ELSE IF (N .LT. 0) THEN
       INFO = -3
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    READ (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=13) A
    RETURN
13  WRITE (ERROR_UNIT,'(2A)') 'BIO_READ_S2 :', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_READ_S2

  SUBROUTINE BIO_WRITE_S2(U, M, N, A, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: U, M, N
    REAL, INTENT(IN) :: A(M,N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (M .LT. 0) THEN
       INFO = -2
    ELSE IF (N .LT. 0) THEN
       INFO = -3
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    WRITE (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=14) A
    RETURN
14  WRITE (ERROR_UNIT,'(2A)') 'BIO_WRITE_S2:', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_WRITE_S2

  SUBROUTINE BIO_READ_C2(U, M, N, A, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: U, M, N
    COMPLEX, INTENT(OUT) :: A(M,N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (M .LT. 0) THEN
       INFO = -2
    ELSE IF (N .LT. 0) THEN
       INFO = -3
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    READ (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=15) A
    RETURN
15  WRITE (ERROR_UNIT,'(2A)') 'BIO_READ_C2 :', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_READ_C2

  SUBROUTINE BIO_WRITE_C2(U, M, N, A, INFO)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: U, M, N
    COMPLEX, INTENT(IN) :: A(M,N)
    INTEGER, INTENT(OUT) :: INFO

    CHARACTER(LEN=IOMSGLEN) :: MSG

    IF (M .LT. 0) THEN
       INFO = -2
    ELSE IF (N .LT. 0) THEN
       INFO = -3
    ELSE
       INFO = 0
    END IF
    IF (INFO .NE. 0) RETURN

    WRITE (UNIT=U, IOSTAT=INFO, IOMSG=MSG, ERR=16) A
    RETURN
16  WRITE (ERROR_UNIT,'(2A)') 'BIO_WRITE_C2:', TRIM(MSG)
    FLUSH(ERROR_UNIT)
  END SUBROUTINE BIO_WRITE_C2
END MODULE BIO
