FUNCTION QCCMP(A, B)  BIND(C,NAME='qccmp_')
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE
  INTEGER, PARAMETER :: WP = QX_WP
  TYPE(c_ptr), INTENT(IN), VALUE :: A, B
  INTEGER(KIND=c_int) :: QCCMP

  REAL(KIND=WP), POINTER :: PA, PB

  CALL C_F_POINTER(A, PA)
  CALL C_F_POINTER(B, PB)
  IF (PA .LT. PB) THEN
     QCCMP = -1_c_int
  ELSE IF (PB .LT. PA) THEN
     QCCMP = 1_c_int
  ELSE ! =
     QCCMP = 0_c_int
  END IF
END FUNCTION QCCMP
