INTERFACE BIN_READ_0
   MODULE PROCEDURE BIN_READ_0A
   MODULE PROCEDURE BIN_READ_0S
   MODULE PROCEDURE BIN_READ_0D
   MODULE PROCEDURE BIN_READ_0C
   MODULE PROCEDURE BIN_READ_0Z
   MODULE PROCEDURE BIN_READ_0I
   MODULE PROCEDURE BIN_READ_0L
END INTERFACE BIN_READ_0

INTERFACE BIN_WRITE_0
   MODULE PROCEDURE BIN_WRITE_0A
   MODULE PROCEDURE BIN_WRITE_0S
   MODULE PROCEDURE BIN_WRITE_0D
   MODULE PROCEDURE BIN_WRITE_0C
   MODULE PROCEDURE BIN_WRITE_0Z
   MODULE PROCEDURE BIN_WRITE_0I
   MODULE PROCEDURE BIN_WRITE_0L
END INTERFACE BIN_WRITE_0

INTERFACE BIN_READ_1
   MODULE PROCEDURE BIN_READ_1S
   MODULE PROCEDURE BIN_READ_1D
   MODULE PROCEDURE BIN_READ_1C
   MODULE PROCEDURE BIN_READ_1Z
   MODULE PROCEDURE BIN_READ_1I
   MODULE PROCEDURE BIN_READ_1L
END INTERFACE BIN_READ_1

INTERFACE BIN_WRITE_1
   MODULE PROCEDURE BIN_WRITE_1S
   MODULE PROCEDURE BIN_WRITE_1D
   MODULE PROCEDURE BIN_WRITE_1C
   MODULE PROCEDURE BIN_WRITE_1Z
   MODULE PROCEDURE BIN_WRITE_1I
   MODULE PROCEDURE BIN_WRITE_1L
END INTERFACE BIN_WRITE_1

INTERFACE BIN_READ_2
   MODULE PROCEDURE BIN_READ_2S
   MODULE PROCEDURE BIN_READ_2D
   MODULE PROCEDURE BIN_READ_2C
   MODULE PROCEDURE BIN_READ_2Z
   MODULE PROCEDURE BIN_READ_2I
   MODULE PROCEDURE BIN_READ_2L
END INTERFACE BIN_READ_2

INTERFACE BIN_WRITE_2
   MODULE PROCEDURE BIN_WRITE_2S
   MODULE PROCEDURE BIN_WRITE_2D
   MODULE PROCEDURE BIN_WRITE_2C
   MODULE PROCEDURE BIN_WRITE_2Z
   MODULE PROCEDURE BIN_WRITE_2I
   MODULE PROCEDURE BIN_WRITE_2L
END INTERFACE BIN_WRITE_2
