INTEGER FUNCTION BLAS_PREPARE()

  IMPLICIT NONE

  IF (.NOT. OMP_GET_NESTED()) CALL OMP_SET_NESTED(.TRUE.)
  IF (OMP_GET_DYNAMIC()) CALL OMP_SET_DYNAMIC(.FALSE.)
#ifdef USE_MKL
  IF (MKL_GET_DYNAMIC()) CALL MKL_SET_DYNAMIC(0)
#ifndef NDEBUG
  BLAS_PREPARE = MKL_PEAK_MEM_USAGE(MKL_PEAK_MEM_ENABLE)
  IF (BLAS_PREPARE .EQ. -1) RETURN
#endif
#endif
  BLAS_PREPARE = OMP_GET_MAX_ACTIVE_LEVELS()

END FUNCTION BLAS_PREPARE

INTEGER FUNCTION BLAS_FINISH()

  IMPLICIT NONE
#ifdef USE_MKL
#ifndef NDEBUG
  INTEGER :: A, B
  INTEGER(4) :: C
  A = MKL_PEAK_MEM_USAGE(MKL_PEAK_MEM)
  B = MKL_PEAK_MEM_USAGE(MKL_PEAK_MEM_DISABLE)
  IF (A .EQ. -1) THEN
     BLAS_FINISH = B
  ELSE IF (B .EQ. -1) THEN
     BLAS_FINISH = -A
  ELSE
     BLAS_FINISH = MAX(A, B)
  END IF
  A = MKL_MEM_STAT(C)
  B = INT(C)
  WRITE (GET_IOUNIT('E'),'(A,I12,A,I12,A,I11,A)') 'MKL memory: peak ',BLAS_FINISH,' B, currently ',A,' B in ',B,' buffers'
#endif
#endif
  BLAS_FINISH = 0

END FUNCTION BLAS_FINISH

INTEGER FUNCTION BLAS_SET_NUM_THREADS(NT)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: NT

#ifdef USE_MKL
  BLAS_SET_NUM_THREADS = MKL_SET_NUM_THREADS_LOCAL(INT(NT,4))
#else
  BLAS_SET_NUM_THREADS = OMP_GET_NUM_THREADS()
  CALL OMP_SET_NUM_THREADS(NT)
#endif

END FUNCTION BLAS_SET_NUM_THREADS
