INTEGER FUNCTION BLAS_PREPARE()

#ifdef USE_MKL
  USE MKL_SERVICE
#endif
  IMPLICIT NONE
  IF (.NOT. OMP_GET_NESTED()) CALL OMP_SET_NESTED(.TRUE.)
  IF (OMP_GET_DYNAMIC()) CALL OMP_SET_DYNAMIC(.FALSE.)
  BLAS_PREPARE = OMP_GET_MAX_ACTIVE_LEVELS()
#ifdef USE_MKL
  IF (MKL_DISABLE_FAST_MM() .EQ. 0) THEN
     BLAS_PREPARE = -1
  ELSE
     IF (MKL_GET_DYNAMIC()) CALL MKL_SET_DYNAMIC(0)
     BLAS_PREPARE = OMP_GET_MAX_ACTIVE_LEVELS()
  END IF
#endif

END FUNCTION BLAS_PREPARE

INTEGER FUNCTION BLAS_SET_NUM_THREADS(NT)

#ifdef USE_MKL
  USE MKL_SERVICE
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NT
  INTEGER(4), INTRINSIC :: INT
  BLAS_SET_NUM_THREADS = MKL_SET_NUM_THREADS_LOCAL(INT(NT,4))
#else
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NT
  BLAS_SET_NUM_THREADS = OMP_GET_NUM_THREADS()
  CALL OMP_SET_NUM_THREADS(NT)
#endif

END FUNCTION BLAS_SET_NUM_THREADS
