INTEGER FUNCTION BLAS_PREPARE(NEST, DYN)

  IMPLICIT NONE

  LOGICAL, INTENT(IN), OPTIONAL :: NEST, DYN

  LOGICAL :: MY_NEST, MY_DYN

  IF (PRESENT(NEST)) THEN
     MY_NEST = NEST
  ELSE
     MY_NEST = .TRUE.
  END IF

  IF (PRESENT(DYN)) THEN
     MY_DYN = DYN
  ELSE
     MY_DYN = .TRUE.
  END IF

  IF (OMP_GET_NESTED() .NEQV. MY_NEST) CALL OMP_SET_NESTED(MY_NEST)
  IF (OMP_GET_DYNAMIC() .NEQV. MY_DYN) CALL OMP_SET_DYNAMIC(MY_DYN)
#ifdef USE_MKL
  SELECT CASE (MKL_GET_DYNAMIC())
  CASE (0_c_int)
     IF (MY_DYN) CALL MKL_SET_DYNAMIC(1_c_int)
  CASE (1_c_int)
     IF (.NOT. MY_DYN) CALL MKL_SET_DYNAMIC(0_c_int)
  END SELECT
#ifndef NDEBUG
  BLAS_PREPARE = INT(MKL_PEAK_MEM_USAGE(MKL_PEAK_MEM_ENABLE))
  IF (BLAS_PREPARE .EQ. -1) RETURN
#endif
#endif
  BLAS_PREPARE = INT(OMP_GET_MAX_ACTIVE_LEVELS())

END FUNCTION BLAS_PREPARE

INTEGER FUNCTION BLAS_FINISH()

  IMPLICIT NONE
#ifdef USE_MKL
#ifndef NDEBUG
  INTEGER :: A, B
  INTEGER(c_int) :: C
  A = MKL_PEAK_MEM_USAGE(MKL_PEAK_MEM)
  B = MKL_PEAK_MEM_USAGE(MKL_PEAK_MEM_DISABLE)
  IF (A .EQ. -1) THEN
     BLAS_FINISH = B
  ELSE IF (B .EQ. -1) THEN
     BLAS_FINISH = -A
  ELSE
     BLAS_FINISH = MAX(A, B)
  END IF
  A = MKL_MEM_STAT(C)
  B = INT(C)
  WRITE (GET_IOUNIT('E'),'(A,I12,A,I12,A,I11,A)') 'MKL memory: peak ',BLAS_FINISH,' B, currently ',A,' B in ',B,' buffers'
#endif
#endif
  BLAS_FINISH = 0

END FUNCTION BLAS_FINISH

INTEGER FUNCTION BLAS_SET_NUM_THREADS(NT)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: NT

#ifdef USE_MKL
  BLAS_SET_NUM_THREADS = INT(MKL_SET_NUM_THREADS_LOCAL(INT(NT,c_int)))
#else
  BLAS_SET_NUM_THREADS = INT(OMP_GET_NUM_THREADS())
  CALL OMP_SET_NUM_THREADS(NT)
#endif

END FUNCTION BLAS_SET_NUM_THREADS
