REAL, PARAMETER :: S_ZERO =  0.0E0
REAL, PARAMETER :: S_ONE  =  1.0E0
REAL, PARAMETER :: S_MONE = -1.0E0
REAL, PARAMETER :: S_TWO  =  2.0E0
REAL, PARAMETER :: S_HALF =  0.5E0

REAL(RWP), PARAMETER :: R_ZERO =  0.0E0_RWP
REAL(RWP), PARAMETER :: R_ONE  =  1.0E0_RWP
REAL(RWP), PARAMETER :: R_MONE = -1.0E0_RWP
REAL(RWP), PARAMETER :: R_TWO  =  2.0E0_RWP
REAL(RWP), PARAMETER :: R_HALF =  0.5E0_RWP

DOUBLE PRECISION, PARAMETER :: D_ZERO =  0.0D0
DOUBLE PRECISION, PARAMETER :: D_ONE  =  1.0D0
DOUBLE PRECISION, PARAMETER :: D_MONE = -1.0D0
DOUBLE PRECISION, PARAMETER :: D_TWO  =  2.0D0
DOUBLE PRECISION, PARAMETER :: D_MTWO = -2.0D0
DOUBLE PRECISION, PARAMETER :: D_HALF =  0.5D0

COMPLEX, PARAMETER :: C_ZERO  = (S_ZERO,S_ZERO)
COMPLEX, PARAMETER :: C_ONE   = ( S_ONE,S_ZERO)
COMPLEX, PARAMETER :: C_MONE  = (S_MONE,S_ZERO)

COMPLEX(RWP), PARAMETER :: W_ZERO  = (R_ZERO,R_ZERO)
COMPLEX(RWP), PARAMETER :: W_ONE   = ( R_ONE,R_ZERO)
COMPLEX(RWP), PARAMETER :: W_MONE  = (R_MONE,R_ZERO)

DOUBLE COMPLEX, PARAMETER :: Z_ZERO  = (D_ZERO,D_ZERO)
DOUBLE COMPLEX, PARAMETER :: Z_ONE   = ( D_ONE,D_ZERO)
DOUBLE COMPLEX, PARAMETER :: Z_MONE  = (D_MONE,D_ZERO)
