INTEGER FUNCTION GET_IOUNIT(TYP)

  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INPUT_UNIT, OUTPUT_UNIT, ERROR_UNIT
  IMPLICIT NONE

  INTEGER, PARAMETER :: NXT = MAX(ERROR_UNIT, INPUT_UNIT, OUTPUT_UNIT) + 1
  CHARACTER, INTENT(IN) :: TYP

  SELECT CASE (TYP)
  CASE ('E', 'e') ! STDERR
     GET_IOUNIT = ERROR_UNIT
  CASE ('I', 'i') ! STDIN
     GET_IOUNIT = INPUT_UNIT
  CASE ('O', 'o') ! STDOUT
     GET_IOUNIT = OUTPUT_UNIT
  CASE ('N', 'n')
     GET_IOUNIT = NXT + INT(OMP_GET_THREAD_NUM())
  CASE DEFAULT
     GET_IOUNIT = -1
  END SELECT

END FUNCTION GET_IOUNIT
