#ifndef NFMA
PURE REAL FUNCTION SFMA(A, B, C)
  IMPLICIT NONE
  REAL, INTENT(IN) :: A, B, C
  !DIR$ FMA
  SFMA = A * B + C
END FUNCTION SFMA
PURE DOUBLE PRECISION FUNCTION DFMA(A, B, C)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN) :: A, B, C
  !DIR$ FMA
  DFMA = A * B + C
END FUNCTION DFMA
#endif

#ifndef USE_INTEL
ELEMENTAL REAL FUNCTION SRSQRT(X)
  IMPLICIT NONE
  REAL, INTENT(IN) :: X
  SRSQRT = S_ONE / SQRT(X)
END FUNCTION SRSQRT
ELEMENTAL DOUBLE PRECISION FUNCTION DRSQRT(X)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN) :: X
  DRSQRT = D_ONE / SQRT(X)
END FUNCTION DRSQRT
PURE SUBROUTINE SSINCOS(X, S, C)
  IMPLICIT NONE
  REAL, INTENT(IN), VALUE :: X
  REAL, INTENT(OUT) :: S, C
  S = SIN(X)
  C = COS(X)
END SUBROUTINE SSINCOS
#endif

#ifdef USE_GNU
PURE SUBROUTINE DSINCOS(X, S, C)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN), VALUE :: X
  DOUBLE PRECISION, INTENT(OUT) :: S, C
  S = SIN(X)
  C = COS(X)
END SUBROUTINE DSINCOS
#endif
