INTERFACE FMA
#ifdef NFMA
   PURE FUNCTION SFMA(A, B, C) BIND(C,NAME='fmaf')
     USE, INTRINSIC :: ISO_C_BINDING
     IMPLICIT NONE
     REAL(c_float), INTENT(IN), VALUE :: A, B, C
     REAL(c_float) :: SFMA
   END FUNCTION SFMA
   PURE FUNCTION DFMA(A, B, C) BIND(C,NAME='fma')
     USE, INTRINSIC :: ISO_C_BINDING
     IMPLICIT NONE
     REAL(c_double), INTENT(IN), VALUE :: A, B, C
     REAL(c_double) :: DFMA
   END FUNCTION DFMA
#else
   MODULE PROCEDURE SFMA, DFMA
#endif
END INTERFACE

INTERFACE RSQRT
#ifdef USE_INTEL
   PURE FUNCTION SRSQRT(X) BIND(C,NAME='invsqrtf')
     USE, INTRINSIC :: ISO_C_BINDING
     IMPLICIT NONE
     REAL(c_float), INTENT(IN), VALUE :: X
     REAL(c_float) :: SRSQRT
   END FUNCTION SRSQRT
   PURE FUNCTION DRSQRT(X) BIND(C,NAME='invsqrt')
     USE, INTRINSIC :: ISO_C_BINDING
     IMPLICIT NONE
     REAL(c_double), INTENT(IN), VALUE :: X
     REAL(c_double) :: DRSQRT
   END FUNCTION DRSQRT
#else
   MODULE PROCEDURE SRSQRT, DRSQRT
#endif
END INTERFACE

INTERFACE SINCOS
#ifdef USE_INTEL
   PURE SUBROUTINE SSINCOS(X, S, C) BIND(C,NAME='sincosf')
     USE, INTRINSIC :: ISO_C_BINDING
     IMPLICIT NONE
     REAL(c_float), INTENT(IN), VALUE :: X
     REAL(c_float), INTENT(OUT) :: S, C
   END SUBROUTINE SSINCOS
#else
   MODULE PROCEDURE SSINCOS
#endif
#ifndef USE_GNU
   PURE SUBROUTINE DSINCOS(X, S, C) BIND(C,NAME='sincos')
     USE, INTRINSIC :: ISO_C_BINDING
     IMPLICIT NONE
     REAL(c_double), INTENT(IN), VALUE :: X
     REAL(c_double), INTENT(OUT) :: S, C
   END SUBROUTINE DSINCOS
#else
   MODULE PROCEDURE DSINCOS
#endif
END INTERFACE

INTERFACE
   PURE SUBROUTINE JSTRAT_INIT(JS, ID, N, INFO) BIND(C,NAME='jstrat_init_f')
     IMPLICIT NONE
     INTEGER, INTENT(OUT) :: JS(*)
     INTEGER, INTENT(IN) :: ID, N
     INTEGER, INTENT(OUT) :: INFO
   END SUBROUTINE JSTRAT_INIT
END INTERFACE

INTERFACE
   PURE SUBROUTINE JSTRAT_NEXT(JS, ARR, INFO) BIND(C,NAME='jstrat_next_f')
     IMPLICIT NONE
     INTEGER, INTENT(INOUT) :: JS(*)
     INTEGER, INTENT(OUT) :: ARR(2,*)
     INTEGER, INTENT(OUT) :: INFO
   END SUBROUTINE JSTRAT_NEXT
END INTERFACE
