#ifdef LOGICAL_KIND
INTEGER, PARAMETER :: LWP = LOGICAL_KIND
#else
INTEGER, PARAMETER :: LWP = KIND(.FALSE.)
#endif

#ifdef INTEGER_KIND
INTEGER, PARAMETER :: IWP = INTEGER_KIND
#else
INTEGER, PARAMETER :: IWP = KIND(0)
#endif

#ifdef REAL_KIND
INTEGER, PARAMETER :: RWP = REAL_KIND
#else
INTEGER, PARAMETER :: RWP = KIND(0.0E0)
#endif

#ifdef DOUBLE_KIND
INTEGER, PARAMETER :: DWP = DOUBLE_KIND
#else
INTEGER, PARAMETER :: DWP = KIND(0.0D0)
#endif
