SUBROUTINE DJACV1_PREPARE_F(STRAT, LDA, M, N, NTHR, LDA0, N0, WORK, LWORK, IWORK, LIWORK, INFO)
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: STRAT, LDA, M, N, NTHR
  DOUBLE PRECISION, INTENT(OUT), ALLOCATABLE :: WORK(:)
  !DIR$ ATTRIBUTES ALIGN: PAGESZ_B:: WORK
!IBM* ALIGN(PAGESZ_B, WORK)
  INTEGER, INTENT(OUT), ALLOCATABLE :: IWORK(:)
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: IWORK
!IBM* ALIGN(MALIGN_B, IWORK)
  INTEGER, INTENT(OUT) :: LDA0, N0, LWORK, LIWORK, INFO

  INTEGER :: JS(JSMLEN), PIV(2,MAX(1,NTHR))
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: JS, PIV
!IBM* ALIGN(MALIGN_B, JS, PIV)

  INTEGER :: NBLK, STEPS, R, MINWRK, I, J

  !DIR$ ASSUME (MOD(LDA,D_VEC_LEN) .EQ. 0)

  INFO = 0

  IF (STRAT .LT. 0) THEN
     INFO = -1
     RETURN
  END IF
  IF ((M .LE. 0) .OR. (M .GT. LDA) .OR. (M .GT. N)) THEN
     INFO = -2
     RETURN
  END IF
  IF ((N .LE. 0) .OR. (N .GT. LDA) .OR. (N .GT. M)) THEN
     INFO = -3
     RETURN
  END IF
  IF ((NTHR .LE. 0) .OR. (NTHR .GT. MAX_TPC)) THEN
     INFO = -4
     RETURN
  END IF

  NBLK = NTHR * 2
  IF (MOD(N,NBLK) .NE. 0) THEN
     INFO = -3
     RETURN
  END IF

  N0 = N / NTHR
  LDA0 = N0
  R = MOD(N0, D_VEC_LEN)
  IF (R .NE. 0) LDA0 = LDA0 + (D_VEC_LEN - R)

  LWORK = (LDA0 * N0) * 2 * NTHR
  IF (ALLOCATED(WORK)) DEALLOCATE(WORK)
  ALLOCATE(WORK(LWORK))

  CALL JSTRAT_INIT(JS, STRAT, NBLK, STEPS)
  IF (STEPS .LE. 0) THEN
     INFO = -1
     RETURN
  END IF

  MINWRK = STEPS * NTHR
  R = MOD(MINWRK, I_VEC_LEN)
  IF (R .NE. 0) MINWRK = MINWRK + (I_VEC_LEN - R)

  LIWORK = 2 * MINWRK
  IF (ALLOCATED(IWORK)) DEALLOCATE(IWORK)
  ALLOCATE(IWORK(LIWORK))

  R = 1
  DO I = 1, STEPS
     CALL JSTRAT_NEXT(JS, PIV, INFO)
     IF (INFO .NE. NTHR) THEN
        INFO = 0
        RETURN
     END IF
     DO J = 1, NTHR
        IWORK(R) = PIV(1,J) * LDA ! P
        IWORK(MINWRK + R) = PIV(2,J) * LDA ! Q
        R = R + 1
     END DO
  END DO

  INFO = STEPS
END SUBROUTINE DJACV1_PREPARE_F

SUBROUTINE DJACV1_EXECUTE_F
  IMPLICIT NONE
END SUBROUTINE DJACV1_EXECUTE_F
