PROGRAM xLASVD

  USE LASVD
  IMPLICIT NONE

#ifdef FA
#ifndef FW
#define FW
#endif
#endif

#ifdef GEJSV
  CHARACTER :: JOBA, JOBU, JOBV, JOBR, JOBT, JOBP
  INTEGER :: M, N, LDA, LDU, LDV, LWORK, LIWORK, INFO
#ifdef SLASVD
  REAL, ALLOCATABLE :: A(:,:), U(:,:), V(:,:), SVA(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,U,V,SVA
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,U,V,SVA
#endif
  REAL, ALLOCATABLE :: WORK(:)
  INTEGER, ALLOCATABLE :: IWORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK,IWORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK,IWORK
#endif
!IBM* ALIGN(MALIGN_B, A,U,V,SVA, WORK,IWORK)
#endif
#ifdef DLASVD
  DOUBLE PRECISION, ALLOCATABLE :: A(:,:), U(:,:), V(:,:), SVA(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,U,V,SVA
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,U,V,SVA
#endif
  DOUBLE PRECISION, ALLOCATABLE :: WORK(:)
  INTEGER, ALLOCATABLE :: IWORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK,IWORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK,IWORK
#endif
!IBM* ALIGN(MALIGN_B, A,U,V,SVA, WORK,IWORK)
#endif
#ifdef CLASVD
  COMPLEX, ALLOCATABLE :: A(:,:), U(:,:), V(:,:)
  REAL, ALLOCATABLE :: SVA(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,U,V,SVA
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,U,V,SVA
#endif
  COMPLEX, ALLOCATABLE :: WORK(:)
  REAL, ALLOCATABLE :: RWORK(:)
  INTEGER, ALLOCATABLE :: IWORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK,RWORK,IWORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK,RWORK,IWORK
#endif
!IBM* ALIGN(MALIGN_B, A,U,V,SVA, WORK,RWORK,IWORK)
  INTEGER :: LRWORK
#endif
#ifdef ZLASVD
  DOUBLE COMPLEX, ALLOCATABLE :: A(:,:), U(:,:), V(:,:)
  DOUBLE PRECISION, ALLOCATABLE :: SVA(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,U,V,SVA
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,U,V,SVA
#endif
  DOUBLE COMPLEX, ALLOCATABLE :: WORK(:)
  DOUBLE PRECISION, ALLOCATABLE :: RWORK(:)
  INTEGER, ALLOCATABLE :: IWORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK,RWORK,IWORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK,RWORK,IWORK
#endif
!IBM* ALIGN(MALIGN_B, A,U,V,SVA, WORK,RWORK,IWORK)
  INTEGER :: LRWORK
#endif
#endif

#ifdef GESVJ
  CHARACTER :: JOBA, JOBU, JOBV
  INTEGER :: M, N, LDA, MV, LDV, LWORK, INFO
#ifdef SLASVD
  REAL, ALLOCATABLE :: A(:,:), V(:,:), SVA(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,V,SVA
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,V,SVA
#endif
  REAL, ALLOCATABLE :: WORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK
#endif
!IBM* ALIGN(MALIGN_B, A,V,SVA, WORK)
#endif
#ifdef DLASVD
  DOUBLE PRECISION, ALLOCATABLE :: A(:,:), V(:,:), SVA(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,V,SVA
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,V,SVA
#endif
  DOUBLE PRECISION, ALLOCATABLE :: WORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK
#endif
!IBM* ALIGN(MALIGN_B, A,V,SVA, WORK)
#endif
#ifdef CLASVD
  COMPLEX, ALLOCATABLE :: A(:,:), V(:,:)
  REAL, ALLOCATABLE :: SVA(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,V,SVA
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,V,SVA
#endif
  COMPLEX, ALLOCATABLE :: WORK(:)
  REAL, ALLOCATABLE :: RWORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK,RWORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK,RWORK
#endif
!IBM* ALIGN(MALIGN_B, A,V,SVA, WORK,RWORK)
  INTEGER :: LRWORK
#endif
#ifdef ZLASVD
  DOUBLE COMPLEX, ALLOCATABLE :: A(:,:), V(:,:)
  DOUBLE PRECISION, ALLOCATABLE :: SVA(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,V,SVA
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,V,SVA
#endif
  DOUBLE COMPLEX, ALLOCATABLE :: WORK(:)
  DOUBLE PRECISION, ALLOCATABLE :: RWORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK,RWORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK,RWORK
#endif
!IBM* ALIGN(MALIGN_B, A,V,SVA, WORK,RWORK)
  INTEGER :: LRWORK
#endif
#endif

#ifdef GESVD
  CHARACTER :: JOBU, JOBVT
  INTEGER :: M, N, LDA, LDU, LDVT, LWORK, INFO
#ifdef SLASVD
  REAL, ALLOCATABLE :: A(:,:), U(:,:), VT(:,:), S(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,U,VT,S
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,U,VT,S
#endif
  REAL, ALLOCATABLE :: WORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK
#endif
!IBM* ALIGN(MALIGN_B, A,U,VT,S, WORK)
#endif
#ifdef DLASVD
  DOUBLE PRECISION, ALLOCATABLE :: A(:,:), U(:,:), VT(:,:), S(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,U,VT,S
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,U,VT,S
#endif
  DOUBLE PRECISION, ALLOCATABLE :: WORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK
#endif
!IBM* ALIGN(MALIGN_B, A,U,VT,S, WORK)
#endif
#ifdef CLASVD
  COMPLEX, ALLOCATABLE :: A(:,:), U(:,:), VT(:,:)
  REAL, ALLOCATABLE :: S(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,U,VT,S
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,U,VT,S
#endif
  COMPLEX, ALLOCATABLE :: WORK(:)
  REAL, ALLOCATABLE :: RWORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK,RWORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK,RWORK
#endif
!IBM* ALIGN(MALIGN_B, A,U,VT,S, WORK,RWORK)
  INTEGER :: LRWORK
#endif
#ifdef ZLASVD
  DOUBLE COMPLEX, ALLOCATABLE :: A(:,:), U(:,:), VT(:,:)
  DOUBLE PRECISION, ALLOCATABLE :: S(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,U,VT,S
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,U,VT,S
#endif
  DOUBLE COMPLEX, ALLOCATABLE :: WORK(:)
  DOUBLE PRECISION, ALLOCATABLE :: RWORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK,RWORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK,RWORK
#endif
!IBM* ALIGN(MALIGN_B, A,U,VT,S, WORK,RWORK)
  INTEGER :: LRWORK
#endif
#endif

#ifdef GESDD
  CHARACTER :: JOBZ
  INTEGER :: M, N, LDA, LDU, LDVT, LWORK, LIWORK, INFO
#ifdef SLASVD
  REAL, ALLOCATABLE :: A(:,:), U(:,:), VT(:,:), S(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,U,VT,S
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,U,VT,S
#endif
  REAL, ALLOCATABLE :: WORK(:)
  INTEGER, ALLOCATABLE :: IWORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK,IWORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK,IWORK
#endif
!IBM* ALIGN(MALIGN_B, A,U,VT,S, WORK,IWORK)
#endif
#ifdef DLASVD
  DOUBLE PRECISION, ALLOCATABLE :: A(:,:), U(:,:), VT(:,:), S(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,U,VT,S
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,U,VT,S
#endif
  DOUBLE PRECISION, ALLOCATABLE :: WORK(:)
  INTEGER, ALLOCATABLE :: IWORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK,IWORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK,IWORK
#endif
!IBM* ALIGN(MALIGN_B, A,U,VT,S, WORK,IWORK)
#endif
#ifdef CLASVD
  COMPLEX, ALLOCATABLE :: A(:,:), U(:,:), VT(:,:)
  REAL, ALLOCATABLE :: S(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,U,VT,S
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,U,VT,S
#endif
  COMPLEX, ALLOCATABLE :: WORK(:)
  REAL, ALLOCATABLE :: RWORK(:)
  INTEGER, ALLOCATABLE :: IWORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK,RWORK,IWORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK,RWORK,IWORK
#endif
!IBM* ALIGN(MALIGN_B, A,U,VT,S, WORK,RWORK,IWORK)
  INTEGER :: LRWORK
#endif
#ifdef ZLASVD
  DOUBLE COMPLEX, ALLOCATABLE :: A(:,:), U(:,:), VT(:,:)
  DOUBLE PRECISION, ALLOCATABLE :: S(:)
#ifdef FA
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: A,U,VT,S
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: A,U,VT,S
#endif
  DOUBLE COMPLEX, ALLOCATABLE :: WORK(:)
  DOUBLE PRECISION, ALLOCATABLE :: RWORK(:)
  INTEGER, ALLOCATABLE :: IWORK(:)
#ifdef FW
  !DIR$ ATTRIBUTES FASTMEM, ALIGN: MALIGN_B:: WORK,RWORK,IWORK
#else
  !DIR$ ATTRIBUTES ALIGN: MALIGN_B:: WORK,RWORK,IWORK
#endif
!IBM* ALIGN(MALIGN_B, A,U,VT,S, WORK,RWORK,IWORK)
  INTEGER :: LRWORK
#endif
#endif

#ifdef SLASVD
#ifdef CMPLXSVD
#undef CMPLXSVD
#endif
#ifndef REALSVD
#define REALSVD
#endif
#ifdef GEJSV
  EXTERNAL :: SGEJSV
#endif
#ifdef GESVJ
  EXTERNAL :: SGESVJ
#endif
#ifdef GESVD
  REAL :: WRK(1)
  EXTERNAL :: SGESVD
#endif
#ifdef GESDD
  REAL :: WRK(1)
  EXTERNAL :: SGESDD
#endif
#endif

#ifdef DLASVD
#ifdef CMPLXSVD
#undef CMPLXSVD
#endif
#ifndef REALSVD
#define REALSVD
#endif
#ifdef GEJSV
  EXTERNAL :: DGEJSV
#endif
#ifdef GESVJ
  EXTERNAL :: DGESVJ
#endif
#ifdef GESVD
  DOUBLE PRECISION :: WRK(1)
  EXTERNAL :: DGESVD
#endif
#ifdef GESDD
  DOUBLE PRECISION :: WRK(1)
  EXTERNAL :: DGESDD
#endif
#endif

#ifdef CLASVD
#ifndef CMPLXSVD
#define CMPLXSVD
#endif
#ifdef REALSVD
#undef REALSVD
#endif
#ifdef GEJSV
  EXTERNAL :: CGEJSV
#endif
#ifdef GESVJ
  EXTERNAL :: CGESVJ
#endif
#ifdef GESVD
  COMPLEX :: WRK(1)
  EXTERNAL :: CGESVD
#endif
#ifdef GESDD
  COMPLEX :: WRK(1)
  EXTERNAL :: CGESDD
#endif
#endif

#ifdef ZLASVD
#ifndef CMPLXSVD
#define CMPLXSVD
#endif
#ifdef REALSVD
#undef REALSVD
#endif
#ifdef GEJSV
  EXTERNAL :: ZGEJSV
#endif
#ifdef GESVJ
  EXTERNAL :: ZGESVJ
#endif
#ifdef GESVD
  DOUBLE COMPLEX :: WRK(1)
  EXTERNAL :: ZGESVD
#endif
#ifdef GESDD
  DOUBLE COMPLEX :: WRK(1)
  EXTERNAL :: ZGESDD
#endif
#endif

  INTEGER :: IOU
  INTEGER :: CLK(3)
  CHARACTER(LEN=256) :: F
  LOGICAL, EXTERNAL :: LSAME

  INFO = 0

#ifdef GEJSV
  CALL READCL(JOBA, JOBU, JOBV, JOBR, JOBT, JOBP, M, N, LDA, LDU, LDV, F, INFO)
#endif

#ifdef GESVJ
  CALL READCL(JOBA, JOBU, JOBV, M, N, LDA, MV, LDV, F, INFO)
#endif

#ifdef GESVD
  CALL READCL(JOBU, JOBVT, M, N, LDA, LDU, LDVT, F, INFO)
#endif

#ifdef GESDD
  CALL READCL(JOBZ, M, N, LDA, LDU, LDVT, F, INFO)
#endif

  IF (INFO .NE. 0) THEN
     PRINT *, INFO
     STOP 'Check the command line!'
  END IF
  IF (LEN_TRIM(F) .LE. 0) STOP 'F should be a file path!'

  IF ((LDA .GE. M) .AND. (M .GT. 0) .AND. (N .GT. 0)) THEN
     ALLOCATE(A(LDA, N))
  ELSE
     STOP 'LDA >= M > 0 & N > 0'
  END IF

#ifndef GESVJ
  IF ((LDU .GE. M) .AND. (M .GT. 0)) THEN
#ifdef GEJSV
     IF (LSAME(JOBU,'F')) THEN
        ALLOCATE(U(LDU, M))
     ELSE IF ((.NOT. LSAME(JOBU,'N')) .OR. (LSAME(JOBT,'T') .AND. (M .EQ. N))) THEN
        ALLOCATE(U(LDU, N))
     END IF
#endif
#ifdef GESVD
     IF (LSAME(JOBU,'A')) THEN
        ALLOCATE(U(LDU, M))
     ELSE IF (LSAME(JOBU,'S')) THEN
        IF (MIN(M,N) .GT. 0) THEN
           ALLOCATE(U(LDU, MIN(M,N)))
        ELSE
           STOP 'N > 0'
        END IF
     END IF
#endif
#ifdef GESDD
     IF (LSAME(JOBZ,'A')) THEN
        ALLOCATE(U(LDU, M))
     ELSE IF (LSAME(JOBZ,'S')) THEN
        IF (MIN(M,N) .GT. 0) THEN
           ALLOCATE(U(LDU, MIN(M,N)))
        ELSE
           STOP 'N > 0'
        END IF
     END IF
#endif
  ELSE
     STOP 'LDU >= M > 0'
  END IF
#endif

#ifdef GEJSV
  IF ((LDV .GE. N) .AND. (N .GT. 0)) THEN
     IF ((.NOT. LSAME(JOBV,'N')) .OR. (LSAME(JOBT,'T') .AND. (M .EQ. N))) ALLOCATE(V(LDV, N))
  ELSE
     STOP 'LDV >= N > 0'
  END IF
  ALLOCATE(SVA(N))
#endif

#ifdef GESVJ
  IF ((LDV .GE. MV) .AND. (MV .GT. 0)) THEN
     IF (.NOT. LSAME(JOBV,'N')) ALLOCATE(V(LDV, N))
  ELSE
     STOP 'LDV >= MV > 0'
  END IF
  ALLOCATE(SVA(N))
#endif

#ifdef GESVD
  IF (LSAME(JOBVT,'A')) THEN
     IF ((LDVT .GE. N) .AND. (N .GT. 0)) THEN
        ALLOCATE(VT(LDVT, N))
     ELSE
        STOP 'LDVT >= N > 0'
     END IF
  ELSE IF (LSAME(JOBVT,'S')) THEN
     IF ((LDVT .GE. MIN(M,N)) .AND. (MIN(M,N) .GT. 0)) THEN
        ALLOCATE(VT(LDVT, N))
     ELSE
        STOP 'LDVT >= MIN(M,N) > 0'
     END IF
  END IF
  ALLOCATE(S(MIN(M,N)))
#endif

#ifdef GESDD
  IF (LSAME(JOBZ,'A') .OR. (LSAME(JOBZ,'O') .AND. (M .GE. N))) THEN
     IF ((LDVT .GE. N) .AND. (N .GT. 0)) THEN
        ALLOCATE(VT(LDVT, N))
     ELSE
        STOP 'LDVT >= N > 0'
     END IF
  ELSE IF (LSAME(JOBZ,'S')) THEN
     IF ((LDVT .GE. MIN(M,N)) .AND. (MIN(M,N) .GT. 0)) THEN
        ALLOCATE(VT(LDVT, N))
     ELSE
        STOP 'LDVT >= MIN(M,N) > 0'
     END IF
  END IF
  ALLOCATE(S(MIN(M,N)))
#endif

#ifdef GEJSV
  ! TODO: more elaborate workspace query
#ifdef CMPLXSVD
  LRWORK = MAX(7, N + 2 * M)
  LIWORK = MAX(3, 2 * N + M)
  LWORK = MAX(1, N * (5 + 2 * N))
#else
  LIWORK = MAX(3, M + 3 * N)
  LWORK = MAX(2 * M + N, N * (6 + 2 * N) + 6)
#endif
#endif

#ifdef GESVJ
  ! TODO: check the workspaces' lengths
#ifdef CMPLXSVD
  LRWORK = MAX(6, M + N)
#endif
  LWORK = MAX(6, M + N)
#endif

#ifdef GESVD
  ! TODO: check LRWORK
#ifdef CMPLXSVD
  LRWORK = MAX(1, 5 * MIN(M,N))
#endif
  LWORK = -1
#ifdef SLASVD
  CALL SGESVD(JOBU, JOBVT, M, N, A, LDA, S, U, LDU, VT, LDVT, WRK, LWORK, INFO)
#endif
#ifdef DLASVD
  CALL DGESVD(JOBU, JOBVT, M, N, A, LDA, S, U, LDU, VT, LDVT, WRK, LWORK, INFO)
#endif
#ifdef CLASVD
  CALL CGESVD(JOBU, JOBVT, M, N, A, LDA, S, U, LDU, VT, LDVT, WRK, LWORK, RWORK, INFO)
#endif
#ifdef ZLASVD
  CALL ZGESVD(JOBU, JOBVT, M, N, A, LDA, S, U, LDU, VT, LDVT, WRK, LWORK, RWORK, INFO)
#endif
  IF (INFO .EQ. 0) THEN
     LWORK = CEILING(DBLE(WRK(1)))
  ELSE
     STOP 'GESVD workspace query'
  END IF
#endif

#ifdef GESDD
  ! TODO: check LRWORK, LIWORK
#ifdef CMPLXSVD
  IF (LSAME(JOBZ,'N')) THEN
     LRWORK = MAX(1, 7 * MIN(M,N))
  ELSE
     LRWORK = MAX(1, MIN(M,N) * MAX(5 * MIN(M,N) + 7, 2 * MAX(M,N) + 2 * MIN(M,N) + 1))
  END IF
#endif
  LIWORK = MAX(1, 8 * MIN(M,N))
  LWORK = -1
#ifdef SLASVD
  CALL SGESDD(JOBZ, M, N, A, LDA, S, U, LDU, VT, LDVT, WRK, LWORK, IWORK, INFO)
#endif
#ifdef DLASVD
  CALL DGESDD(JOBZ, M, N, A, LDA, S, U, LDU, VT, LDVT, WRK, LWORK, IWORK, INFO)
#endif
#ifdef CLASVD
  CALL CGESDD(JOBZ, M, N, A, LDA, S, U, LDU, VT, LDVT, WRK, LWORK, RWORK, IWORK, INFO)
#endif
#ifdef ZLASVD
  CALL ZGESDD(JOBZ, M, N, A, LDA, S, U, LDU, VT, LDVT, WRK, LWORK, RWORK, IWORK, INFO)
#endif
  IF (INFO .EQ. 0) THEN
     LWORK = CEILING(DBLE(WRK(1)))
  ELSE
     STOP 'GESDD workspace query'
  END IF
#endif

  PRINT *, 'LWORK:', LWORK
  IF (LWORK .GT. 0) ALLOCATE(WORK(LWORK))

#ifdef CMPLXSVD
  PRINT *, 'LRWORK:', LRWORK
  IF (LRWORK .GT. 0) ALLOCATE(RWORK(LRWORK))
#endif

#ifdef GEJSV
  PRINT *, 'LIWORK:', LIWORK
  IF (LIWORK .GT. 0) ALLOCATE(IWORK(LIWORK))
#endif
#ifdef GESDD
  PRINT *, 'LIWORK:', LIWORK
  IF (LIWORK .GT. 0) ALLOCATE(IWORK(LIWORK))
#endif

  IOU = GET_IOUNIT('N')
  IF (IOU .LT. 0) STOP 'GET_IOUNIT(N)'

  CALL BIN_OPEN(IOU, TRIM(F), 'OLD', 'READ', INFO)
  IF (INFO .NE. 0) STOP 'BIN_OPEN(F)'

#ifdef SLASVD
  CALL BIN_READ_2S(IOU, LDA, A, M, N, INFO)
  IF (INFO .NE. 0) STOP 'BIN_READ_2S(F)'
#endif
#ifdef DLASVD
  CALL BIN_READ_2D(IOU, LDA, A, M, N, INFO)
  IF (INFO .NE. 0) STOP 'BIN_READ_2D(F)'
#endif
#ifdef CLASVD
  CALL BIN_READ_2C(IOU, LDA, A, M, N, INFO)
  IF (INFO .NE. 0) STOP 'BIN_READ_2C(F)'
#endif
#ifdef ZLASVD
  CALL BIN_READ_2Z(IOU, LDA, A, M, N, INFO)
  IF (INFO .NE. 0) STOP 'BIN_READ_2Z(F)'
#endif

  CALL BIN_CLOSE(IOU, INFO)
  IF (INFO .NE. 0) STOP 'BIN_CLOSE(F)'

  CALL TIMER_START(CLK)

#ifdef GEJSV
#ifdef SLASVD
  CALL SGEJSV(JOBA, JOBU, JOBV, JOBR, JOBT, JOBP, M, N, A, LDA, SVA, U, LDU, V, LDV, WORK, LWORK, IWORK, INFO)
#endif
#ifdef DLASVD
  CALL DGEJSV(JOBA, JOBU, JOBV, JOBR, JOBT, JOBP, M, N, A, LDA, SVA, U, LDU, V, LDV, WORK, LWORK, IWORK, INFO)
#endif
#ifdef CLASVD
  CALL CGEJSV(JOBA, JOBU, JOBV, JOBR, JOBT, JOBP, M, N, A, LDA, SVA, U, LDU, V, LDV, WORK, LWORK, RWORK, LRWORK, IWORK, INFO)
#endif
#ifdef ZLASVD
  CALL ZGEJSV(JOBA, JOBU, JOBV, JOBR, JOBT, JOBP, M, N, A, LDA, SVA, U, LDU, V, LDV, WORK, LWORK, RWORK, LRWORK, IWORK, INFO)
#endif
#endif

#ifdef GESVJ
#ifdef SLASVD
  CALL SGESVJ(JOBA, JOBU, JOBV, M, N, A, LDA, SVA, MV, V, LDV, WORK, LWORK, INFO)
#endif
#ifdef DLASVD
  CALL DGESVJ(JOBA, JOBU, JOBV, M, N, A, LDA, SVA, MV, V, LDV, WORK, LWORK, INFO)
#endif
#ifdef CLASVD
  CALL CGESVJ(JOBA, JOBU, JOBV, M, N, A, LDA, SVA, MV, V, LDV, WORK, LWORK, RWORK, LRWORK, INFO)
#endif
#ifdef ZLASVD
  CALL ZGESVJ(JOBA, JOBU, JOBV, M, N, A, LDA, SVA, MV, V, LDV, WORK, LWORK, RWORK, LRWORK, INFO)
#endif
#endif

#ifdef GESVD
#ifdef SLASVD
  CALL SGESVD(JOBU, JOBVT, M, N, A, LDA, S, U, LDU, VT, LDVT, WORK, LWORK, INFO)
#endif
#ifdef DLASVD
  CALL DGESVD(JOBU, JOBVT, M, N, A, LDA, S, U, LDU, VT, LDVT, WORK, LWORK, INFO)
#endif
#ifdef CLASVD
  CALL CGESVD(JOBU, JOBVT, M, N, A, LDA, S, U, LDU, VT, LDVT, WORK, LWORK, RWORK, INFO)
#endif
#ifdef ZLASVD
  CALL ZGESVD(JOBU, JOBVT, M, N, A, LDA, S, U, LDU, VT, LDVT, WORK, LWORK, RWORK, INFO)
#endif
#endif

#ifdef GESDD
#ifdef SLASVD
  CALL SGESDD(JOBZ, M, N, A, LDA, S, U, LDU, VT, LDVT, WORK, LWORK, IWORK, INFO)
#endif
#ifdef DLASVD
  CALL DGESDD(JOBZ, M, N, A, LDA, S, U, LDU, VT, LDVT, WORK, LWORK, IWORK, INFO)
#endif
#ifdef CLASVD
  CALL CGESDD(JOBZ, M, N, A, LDA, S, U, LDU, VT, LDVT, WORK, LWORK, RWORK, IWORK, INFO)
#endif
#ifdef ZLASVD
  CALL ZGESDD(JOBZ, M, N, A, LDA, S, U, LDU, VT, LDVT, WORK, LWORK, RWORK, IWORK, INFO)
#endif
#endif

  CALL TIMER_STOP(CLK)
  IF (INFO .NE. 0) PRINT *, INFO
  CALL TIMER_PRINT(CLK)

#ifdef GEJSV
  IF (ALLOCATED(IWORK)) DEALLOCATE(IWORK)
#endif
#ifdef GESDD
  IF (ALLOCATED(IWORK)) DEALLOCATE(IWORK)
#endif

#ifdef CMPLXSVD
  IF (ALLOCATED(RWORK)) DEALLOCATE(RWORK)
#endif

  IF (ALLOCATED(WORK)) DEALLOCATE(WORK)

#ifdef GEJSV
  IF (ALLOCATED(SVA)) DEALLOCATE(SVA)
  IF (ALLOCATED(V)) DEALLOCATE(V)
#endif
#ifdef GESVJ
  IF (ALLOCATED(SVA)) DEALLOCATE(SVA)
  IF (ALLOCATED(V)) DEALLOCATE(V)
#endif
#ifdef GESVD
  IF (ALLOCATED(S)) DEALLOCATE(S)
  IF (ALLOCATED(VT)) DEALLOCATE(VT)
#endif
#ifdef GESDD
  IF (ALLOCATED(S)) DEALLOCATE(S)
  IF (ALLOCATED(VT)) DEALLOCATE(VT)
#endif

#ifndef GESVJ
  IF (ALLOCATED(U)) DEALLOCATE(U)
#endif

  IF (ALLOCATED(A)) DEALLOCATE(A)

CONTAINS

#ifdef GEJSV
  SUBROUTINE READCL(JOBA, JOBU, JOBV, JOBR, JOBT, JOBP, M, N, LDA, LDU, LDV, F, INFO)
    IMPLICIT NONE

    CHARACTER, INTENT(OUT) :: JOBA, JOBU, JOBV, JOBR, JOBT, JOBP
    INTEGER, INTENT(OUT) :: M, N, LDA, LDU, LDV, INFO
    CHARACTER(LEN=*), INTENT(OUT) :: F

    INFO = COMMAND_ARGUMENT_COUNT()
    IF (INFO .EQ. 13) THEN
       CALL GET_COMMAND_ARGUMENT(1, JOBA)
       CALL GET_COMMAND_ARGUMENT(2, JOBU)
       CALL GET_COMMAND_ARGUMENT(3, JOBV)
       CALL GET_COMMAND_ARGUMENT(4, JOBR)
       CALL GET_COMMAND_ARGUMENT(5, JOBT)
       CALL GET_COMMAND_ARGUMENT(6, JOBP)
       CALL GET_COMMAND_ARGUMENT(7, F)
       READ (F,*) M
       CALL GET_COMMAND_ARGUMENT(8, F)
       READ (F,*) N
       CALL GET_COMMAND_ARGUMENT(9, F)
       READ (F,*) LDA
       CALL GET_COMMAND_ARGUMENT(10, F)
       READ (F,*) LDU
       CALL GET_COMMAND_ARGUMENT(11, F)
       READ (F,*) LDV
       CALL GET_COMMAND_ARGUMENT(13, F)
    ELSE
#ifdef SLASVD
       PRINT *, 'SGEJSV.exe JOBA JOBU JOBV JOBR JOBT JOBP M N LDA LDU LDV F'
#endif
#ifdef DLASVD
       PRINT *, 'DGEJSV.exe JOBA JOBU JOBV JOBR JOBT JOBP M N LDA LDU LDV F'
#endif
#ifdef CLASVD
       PRINT *, 'CGEJSV.exe JOBA JOBU JOBV JOBR JOBT JOBP M N LDA LDU LDV F'
#endif
#ifdef ZLASVD
       PRINT *, 'ZGEJSV.exe JOBA JOBU JOBV JOBR JOBT JOBP M N LDA LDU LDV F'
#endif
    END IF
    INFO = INFO - 13
  END SUBROUTINE READCL
#endif

#ifdef GESVJ
  SUBROUTINE READCL(JOBA, JOBU, JOBV, M, N, LDA, MV, LDV, F, INFO)
    IMPLICIT NONE

    CHARACTER, INTENT(OUT) :: JOBA, JOBU, JOBV
    INTEGER, INTENT(OUT) :: M, N, LDA, MV, LDV, INFO
    CHARACTER(LEN=*), INTENT(OUT) :: F

    INFO = COMMAND_ARGUMENT_COUNT()
    IF (INFO .EQ. 9) THEN
       CALL GET_COMMAND_ARGUMENT(1, JOBA)
       CALL GET_COMMAND_ARGUMENT(2, JOBU)
       CALL GET_COMMAND_ARGUMENT(3, JOBV)
       CALL GET_COMMAND_ARGUMENT(4, F)
       READ (F,*) M
       CALL GET_COMMAND_ARGUMENT(5, F)
       READ (F,*) N
       CALL GET_COMMAND_ARGUMENT(6, F)
       READ (F,*) LDA
       CALL GET_COMMAND_ARGUMENT(7, F)
       READ (F,*) MV
       CALL GET_COMMAND_ARGUMENT(8, F)
       READ (F,*) LDV
       CALL GET_COMMAND_ARGUMENT(9, F)
    ELSE
#ifdef SLASVD
       PRINT *, 'SGESVJ.exe JOBA JOBU JOBV M N LDA MV LDV F'
#endif
#ifdef DLASVD
       PRINT *, 'DGESVJ.exe JOBA JOBU JOBV M N LDA MV LDV F'
#endif
#ifdef CLASVD
       PRINT *, 'CGESVJ.exe JOBA JOBU JOBV M N LDA MV LDV F'
#endif
#ifdef ZLASVD
       PRINT *, 'ZGESVJ.exe JOBA JOBU JOBV M N LDA MV LDV F'
#endif
    END IF
    INFO = INFO - 9
  END SUBROUTINE READCL
#endif

#ifdef GESVD
  SUBROUTINE READCL(JOBU, JOBVT, M, N, LDA, LDU, LDVT, F, INFO)
    IMPLICIT NONE

    CHARACTER, INTENT(OUT) :: JOBU, JOBVT
    INTEGER, INTENT(OUT) :: M, N, LDA, LDU, LDVT, INFO
    CHARACTER(LEN=*), INTENT(OUT) :: F

    INFO = COMMAND_ARGUMENT_COUNT()
    IF (INFO .EQ. 8) THEN
       CALL GET_COMMAND_ARGUMENT(1, JOBU)
       CALL GET_COMMAND_ARGUMENT(2, JOBVT)
       CALL GET_COMMAND_ARGUMENT(3, F)
       READ (F,*) M
       CALL GET_COMMAND_ARGUMENT(4, F)
       READ (F,*) N
       CALL GET_COMMAND_ARGUMENT(5, F)
       READ (F,*) LDA
       CALL GET_COMMAND_ARGUMENT(6, F)
       READ (F,*) LDU
       CALL GET_COMMAND_ARGUMENT(7, F)
       READ (F,*) LDVT
       CALL GET_COMMAND_ARGUMENT(8, F)
    ELSE
#ifdef SLASVD
       PRINT *, 'SGESVD.exe JOBU JOBVT M N LDA LDU LDVT F'
#endif
#ifdef DLASVD
       PRINT *, 'DGESVD.exe JOBU JOBVT M N LDA LDU LDVT F'
#endif
#ifdef CLASVD
       PRINT *, 'CGESVD.exe JOBU JOBVT M N LDA LDU LDVT F'
#endif
#ifdef ZLASVD
       PRINT *, 'ZGESVD.exe JOBU JOBVT M N LDA LDU LDVT F'
#endif
    END IF
    INFO = INFO - 8
  END SUBROUTINE READCL
#endif

#ifdef GESDD
  SUBROUTINE READCL(JOBZ, M, N, LDA, LDU, LDVT, F, INFO)
    IMPLICIT NONE

    CHARACTER, INTENT(OUT) :: JOBZ
    INTEGER, INTENT(OUT) :: M, N, LDA, LDU, LDVT, INFO
    CHARACTER(LEN=*), INTENT(OUT) :: F

    INFO = COMMAND_ARGUMENT_COUNT()
    IF (INFO .EQ. 7) THEN
       CALL GET_COMMAND_ARGUMENT(1, JOBZ)
       CALL GET_COMMAND_ARGUMENT(2, F)
       READ (F,*) M
       CALL GET_COMMAND_ARGUMENT(3, F)
       READ (F,*) N
       CALL GET_COMMAND_ARGUMENT(4, F)
       READ (F,*) LDA
       CALL GET_COMMAND_ARGUMENT(5, F)
       READ (F,*) LDU
       CALL GET_COMMAND_ARGUMENT(6, F)
       READ (F,*) LDVT
       CALL GET_COMMAND_ARGUMENT(7, F)
    ELSE
#ifdef SLASVD
       PRINT *, 'SGESDD.exe JOBZ M N LDA LDU LDVT F'
#endif
#ifdef DLASVD
       PRINT *, 'DGESDD.exe JOBZ M N LDA LDU LDVT F'
#endif
#ifdef CLASVD
       PRINT *, 'CGESDD.exe JOBZ M N LDA LDU LDVT F'
#endif
#ifdef ZLASVD
       PRINT *, 'ZGESDD.exe JOBZ M N LDA LDU LDVT F'
#endif
    END IF
    INFO = INFO - 7
  END SUBROUTINE READCL
#endif

END PROGRAM xLASVD
