#ifndef JSTRAT_F_MOD
#define JSTRAT_F_MOD
#endif
MODULE JSTRAT_F
  USE, INTRINSIC :: ISO_C_BINDING
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT32, INT64
  IMPLICIT NONE

  INTEGER(KIND=INT64), PARAMETER :: JSMLEN = 6_INT64
  INTEGER(KIND=INT64), PARAMETER :: JSMLEX = 8_INT64
  INTEGER(KIND=INT64), PARAMETER :: JSROWC = 0_INT64
  INTEGER(KIND=INT64), PARAMETER :: JSCOLC = 1_INT64
  INTEGER(KIND=INT64), PARAMETER :: JSMENC = 2_INT64
  INTEGER(KIND=INT64), PARAMETER :: JSMEWC = 3_INT64
  INTEGER(KIND=INT64), PARAMETER :: JSMMNC = 4_INT64
  INTEGER(KIND=INT64), PARAMETER :: JSMMWC = 5_INT64

  INTERFACE
     PURE SUBROUTINE JSTRAT_INIT(JS, ID, N, INFO) BIND(C,NAME='jstrat_init_f')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64
       IMPLICIT NONE
       INTEGER(KIND=INT64), INTENT(IN), TARGET :: ID, N
       INTEGER(KIND=INT64), INTENT(OUT), TARGET :: JS(*), INFO
     END SUBROUTINE JSTRAT_INIT
  END INTERFACE

  INTERFACE
     PURE SUBROUTINE JSTRAT_NEXT_NC(JS, ARR, INFO) BIND(C,NAME='jstrat_next_f')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64
       IMPLICIT NONE
       INTEGER(KIND=INT64), INTENT(INOUT), TARGET :: JS(*)
       INTEGER(KIND=INT64), INTENT(OUT), TARGET :: ARR(2,*), INFO
     END SUBROUTINE JSTRAT_NEXT_NC
  END INTERFACE

  INTERFACE
     PURE SUBROUTINE JSTRAT_NEXT_WC(JS, ARR, INFO) BIND(C,NAME='jstrat_next_f')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64
       IMPLICIT NONE
       INTEGER(KIND=INT64), INTENT(INOUT), TARGET :: JS(*)
       INTEGER(KIND=INT64), INTENT(OUT), TARGET :: ARR(2,2,*), INFO
     END SUBROUTINE JSTRAT_NEXT_WC
  END INTERFACE

  INTERFACE
     PURE SUBROUTINE JSTRAT_FREE(JS) BIND(C,NAME='jstrat_free_f')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64
       IMPLICIT NONE
       INTEGER(KIND=INT64), INTENT(INOUT), TARGET :: JS(*)
     END SUBROUTINE JSTRAT_FREE
  END INTERFACE

CONTAINS
#include "jstrat_unpack_nc.F90"
#include "jstrat_unpack_wc.F90"
#include "jstrat_sweep_nc.F90"
#include "jstrat_sweep_wc.F90"
END MODULE JSTRAT_F
