PURE SUBROUTINE JSTRAT_UNPACK_NC(JS, ARR, PAIR, INFO)
#ifndef JSTRAT_F_MOD
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT32, INT64
#endif
  IMPLICIT NONE
#ifndef JSTRAT_F_MOD
  INTEGER(KIND=INT64), PARAMETER :: JSMLEN = 6_INT64
  INTEGER(KIND=INT64), PARAMETER :: JSROWC = 0_INT64
  INTEGER(KIND=INT64), PARAMETER :: JSCOLC = 1_INT64
  INTEGER(KIND=INT64), PARAMETER :: JSMENC = 2_INT64
  INTEGER(KIND=INT64), PARAMETER :: JSMMNC = 4_INT64
#endif
  INTEGER(KIND=INT64), INTENT(IN) :: JS(JSMLEN), ARR(2,*)
  INTEGER(KIND=INT64), INTENT(OUT) :: PAIR(2,*)
  INTEGER(KIND=INT64), INTENT(INOUT) :: INFO

  INTEGER(KIND=INT64) :: J, L
  INTEGER(KIND=INT32) :: C(2)
  EQUIVALENCE (L,C)

  SELECT CASE (JS(1))
  CASE (JSROWC, JSCOLC)
     IF (INFO .NE. 1) THEN
        INFO = -2
     ELSE
        PAIR(1,1) = ARR(1,1) + 1
        PAIR(2,1) = ARR(2,1) + 1
     END IF
  CASE (JSMENC)
     IF (INFO .NE. (JS(2) / 2)) THEN
        INFO = -2
     ELSE
        DO J = 1, INFO
           PAIR(1,J) = ARR(1,J) + 1
           PAIR(2,J) = ARR(2,J) + 1
        END DO
     END IF
  CASE (JSMMNC)
     IF (INFO .NE. -(JS(2) / 2)) THEN
        INFO = -2
     ELSE
        INFO = -INFO
        DO J = 1, INFO
           L = ARR(1,J)
           PAIR(1,J) = C(1) + 1
           L = ARR(2,J)
           PAIR(2,J) = C(1) + 1
        END DO
     END IF
  CASE DEFAULT
     INFO = -1
  END SELECT
END SUBROUTINE JSTRAT_UNPACK_NC
