PURE SUBROUTINE SEEDIX(IX, ISEED, INFO)
  IMPLICIT NONE

  INTEGER, INTENT(IN) :: IX
  INTEGER, INTENT(OUT) :: ISEED(4), INFO

  INTEGER, PARAMETER :: ISEEDS(4,2) = &
       RESHAPE( (/ &
       2741, 1223, 1987, 541, &
       3281,  123,  456, 333  &
       /), (/ 4,2 /) )

  IF ((IX .LT. 1) .OR. (IX .GT. 2)) THEN
     INFO = -1
  ELSE
     INFO = 0
     ISEED = ISEEDS(:,IX)
  END IF
END SUBROUTINE SEEDIX
