INTEGER, PARAMETER :: JSMLEN = 6
INTEGER, PARAMETER :: JSROWC = 0
INTEGER, PARAMETER :: JSCOLC = 1
INTEGER, PARAMETER :: JSMENC = 2
INTEGER, PARAMETER :: JSMEWC = 3
INTEGER, PARAMETER :: JSMMNC = 4
INTEGER, PARAMETER :: JSMMWC = 5

INTEGER, PARAMETER :: JSMASK = 4294967295

INTERFACE
   PURE SUBROUTINE JSTRAT_INIT(JS, ID, N, INFO) BIND(C,NAME='jstrat_init_f')
     IMPLICIT NONE
     INTEGER, INTENT(IN), TARGET :: ID, N
     INTEGER, INTENT(OUT), TARGET :: JS(*), INFO
   END SUBROUTINE JSTRAT_INIT
END INTERFACE

INTERFACE
   PURE SUBROUTINE JSTRAT_NEXT(JS, ARR, INFO) BIND(C,NAME='jstrat_next_f')
     IMPLICIT NONE
     INTEGER, INTENT(INOUT), TARGET :: JS(*)
     INTEGER, INTENT(OUT), TARGET :: ARR(2,*), INFO
   END SUBROUTINE JSTRAT_NEXT
END INTERFACE

INTERFACE
   PURE SUBROUTINE JSTRAT_FREE(JS) BIND(C,NAME='jstrat_free_f')
     IMPLICIT NONE
     INTEGER, INTENT(INOUT), TARGET :: JS(*)
   END SUBROUTINE JSTRAT_FREE
END INTERFACE
