  INTERFACE JACV1_PARAMQ
     MODULE PROCEDURE DJACV1_PARAMQ_F
  END INTERFACE JACV1_PARAMQ

  INTERFACE JACV1_PREPARE
     MODULE PROCEDURE DJACV1_PREPARE_F
  END INTERFACE JACV1_PREPARE

  INTERFACE JACV1_EXECUTE
     MODULE PROCEDURE DJACV1_EXECUTE_F
  END INTERFACE JACV1_EXECUTE
