MODULE DATGEN
  USE SEED
  IMPLICIT NONE

  INTEGER, PARAMETER, PRIVATE :: WP = QX_WP

CONTAINS

  SUBROUTINE DGENDAT(N, ISEED, QLAMBDA, QA, DA, QWORK, INFO)
    IMPLICIT NONE

    INTEGER, INTENT(IN) :: N, ISEED(4)
    REAL(KIND=WP), INTENT(IN) :: QLAMBDA(N)
    DOUBLE PRECISION, INTENT(OUT) :: DA(N,N)
    REAL(KIND=WP), INTENT(OUT) :: QA(N,N), QWORK(2*N)
    INTEGER, INTENT(OUT) :: INFO

    INTEGER :: P, Q
    EXTERNAL :: QLAGSY

    INFO = 0

    IF (N .LT. 0) THEN
       INFO = -1
       RETURN
    END IF
    CALL SEEDOK(ISEED, INFO)
    IF (INFO .NE. 0) THEN
       INFO = -2
       RETURN
    END IF

    CALL QLAGSY(N, N-1, QLAMBDA, QA, N, ISEED, QWORK, INFO)
    IF (INFO .NE. 0) RETURN
    IF (INFO .NE. 0) RETURN
#ifdef USE_OPENMP
    !$OMP PARALLEL DO DEFAULT(NONE) SHARED(N,QA,DA) PRIVATE(P,Q)
#endif
    DO Q = 1, N
       DO P = 1, N
          DA(P,Q) = DBLE(QA(P,Q))
       END DO
    END DO
#ifdef USE_OPENMP
    !$OMP END PARALLEL DO
#endif
  END SUBROUTINE DGENDAT

  SUBROUTINE ZGENDAT(N, ISEED, QLAMBDA, XA, ZA, XWORK, INFO)
    IMPLICIT NONE

    INTEGER, INTENT(IN) :: N, ISEED(4)
    REAL(KIND=WP), INTENT(IN) :: QLAMBDA(N)
    DOUBLE COMPLEX, INTENT(OUT) :: ZA(N,N)
    COMPLEX(KIND=WP), INTENT(OUT) :: XA(N,N), XWORK(2*N)
    INTEGER, INTENT(OUT) :: INFO

    INTEGER :: P, Q
    EXTERNAL :: XLAGHE

    INFO = 0

    IF (N .LT. 0) THEN
       INFO = -1
       RETURN
    END IF
    CALL SEEDOK(ISEED, INFO)
    IF (INFO .NE. 0) THEN
       INFO = -2
       RETURN
    END IF

    CALL XLAGHE(N, N-1, QLAMBDA, XA, N, ISEED, XWORK, INFO)
    IF (INFO .NE. 0) RETURN
#ifdef USE_OPENMP
    !$OMP PARALLEL DO DEFAULT(NONE) SHARED(N,XA,ZA) PRIVATE(P,Q)
#endif
    DO Q = 1, N
       DO P = 1, Q-1
          ZA(P,Q) = DCMPLX(DBLE(REAL(XA(P,Q))), DBLE(AIMAG(XA(P,Q))))
       END DO
       ZA(Q,Q) = DCMPLX(DBLE(REAL(XA(Q,Q))), 0.0D0)
       DO P = Q+1, N
          ZA(P,Q) = DCMPLX(DBLE(REAL(XA(P,Q))), DBLE(AIMAG(XA(P,Q))))
       END DO
    END DO
#ifdef USE_OPENMP
    !$OMP END PARALLEL DO
#endif
  END SUBROUTINE ZGENDAT

END MODULE DATGEN
