MODULE SEED
  IMPLICIT NONE

  INTEGER, PARAMETER, PRIVATE :: ISEEDS(4,2) = &
       RESHAPE( (/ &
       2741, 1223, 1987, 541, &
       3281,  123,  456, 333  &
       /), (/ 4,2 /) )

CONTAINS

  PURE SUBROUTINE SEEDIX(IX, ISEED, INFO)
    IMPLICIT NONE

    INTEGER, INTENT(IN) :: IX
    INTEGER, INTENT(OUT) :: ISEED(4), INFO

    IF ((IX .LT. 1) .OR. (IX .GT. 2)) THEN
       INFO = -1
    ELSE
       INFO = 0
       ISEED = ISEEDS(:,IX)
    END IF
  END SUBROUTINE SEEDIX

  PURE SUBROUTINE SEEDOK(ISEED, INFO)
    IMPLICIT NONE

    INTEGER, INTENT(IN) :: ISEED(4)
    INTEGER, INTENT(OUT) :: INFO

    IF ((ISEED(1) .LT. 0) .OR. (ISEED(1) .GT. 4095)) THEN
       INFO = -1
    ELSE IF ((ISEED(2) .LT. 0) .OR. (ISEED(2) .GT. 4095)) THEN
       INFO = -2
    ELSE IF ((ISEED(3) .LT. 0) .OR. (ISEED(3) .GT. 4095)) THEN
       INFO = -3
    ELSE IF ((ISEED(4) .LT. 0) .OR. (ISEED(4) .GT. 4095) .OR. (MOD(ISEED(4),2) .EQ. 0)) THEN
       INFO = -4
    ELSE
       INFO = 0
    END IF
  END SUBROUTINE SEEDOK

END MODULE SEED
