SUBROUTINE DTXTLAM(FN, N, LAM, NPOS, INFO)
  IMPLICIT NONE

  CHARACTER(LEN=*), INTENT(IN) :: FN
  INTEGER, INTENT(IN) :: N
  DOUBLE PRECISION, INTENT(OUT) :: LAM(N)
  INTEGER, INTENT(OUT) :: NPOS, INFO

  DOUBLE PRECISION, PARAMETER :: ZERO = 0.0D0

  INTEGER :: I
  LOGICAL :: FEX

  INQUIRE(FILE=TRIM(FN), EXIST=FEX)
  IF (.NOT. FEX) THEN
    INFO = -1
  ELSE IF (N .LT. 0) THEN
    INFO = -2
  ELSE
    INFO = 0
  END IF
  IF (INFO .NE. 0) RETURN

  OPEN(UNIT=1,FILE=TRIM(FN),ACTION='READ',STATUS='OLD')

  NPOS = 0
  DO I = 1, N
    READ (1,*) LAM(I)
    IF (LAM(I) .GT. ZERO) NPOS = NPOS + 1
  END DO

  CLOSE(UNIT=1)
END SUBROUTINE DTXTLAM
