! ST - OLD, NEW, REPLACE, SCRATCH, UNKNOWN
! RW - READ, WRITE, READWRITE
SUBROUTINE BIN_OPEN(U, FN, ST, RW, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  CHARACTER(LEN=*), INTENT(IN) :: FN, ST, RW
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (LEN_TRIM(FN) .LE. 0) THEN
     INFO = -2
  ELSE IF (LEN_TRIM(ST) .LE. 0) THEN
     INFO = -3
  ELSE IF (LEN_TRIM(RW) .LE. 0) THEN
     INFO = -4
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  OPEN(UNIT=U, FILE=FN, STATUS=ST, ACCESS='STREAM', FORM='UNFORMATTED', ACTION=RW, IOSTAT=INFO)

END SUBROUTINE BIN_OPEN

SUBROUTINE BIN_CLOSE(U, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  INTEGER, INTENT(OUT) :: INFO
 
  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  CLOSE(UNIT=U, IOSTAT=INFO)

END SUBROUTINE BIN_CLOSE

SUBROUTINE BIN_READ_0A(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  CHARACTER(LEN=*), INTENT(OUT) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  READ (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_READ_0A

SUBROUTINE BIN_READ_0S(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  REAL(RWP), INTENT(OUT) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  READ (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_READ_0S

SUBROUTINE BIN_READ_1S(U, X, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, N
  REAL(RWP), INTENT(OUT) :: X(*)
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (N .LT. 0) THEN
     INFO = -3
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (N .EQ. 0) RETURN

  READ (UNIT=U, IOSTAT=INFO) X(1:N)

END SUBROUTINE BIN_READ_1S

SUBROUTINE BIN_READ_2S(U, LDX, X, M, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, LDX, M, N
  REAL(RWP), INTENT(OUT) :: X(LDX,*)
  INTEGER, INTENT(OUT) :: INFO

  INTEGER :: J

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (LDX .LE. 0) THEN
     INFO = -2
  ELSE IF (M .LT. 0) THEN
     INFO = -4
  ELSE IF (M .GT. LDX) THEN
     INFO = -4
  ELSE IF (N .LT. 0) THEN
     INFO = -5
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (M .EQ. 0) RETURN
  IF (N .EQ. 0) RETURN

  IF (M .EQ. LDX) THEN
     J = M * N
     CALL BIN_READ_1S(U, X, J, INFO)
  ELSE
     DO J = 1, N
        CALL BIN_READ_1S(U, X(1,J), M, INFO)
        IF (INFO .NE. 0) RETURN
     END DO
  END IF

END SUBROUTINE BIN_READ_2S

SUBROUTINE BIN_READ_0D(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  REAL(DWP), INTENT(OUT) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  READ (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_READ_0D

SUBROUTINE BIN_READ_1D(U, X, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, N
  REAL(DWP), INTENT(OUT) :: X(*)
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (N .LT. 0) THEN
     INFO = -3
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (N .EQ. 0) RETURN

  READ (UNIT=U, IOSTAT=INFO) X(1:N)

END SUBROUTINE BIN_READ_1D

SUBROUTINE BIN_READ_2D(U, LDX, X, M, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, LDX, M, N
  REAL(DWP), INTENT(OUT) :: X(LDX,*)
  INTEGER, INTENT(OUT) :: INFO

  INTEGER :: J

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (LDX .LE. 0) THEN
     INFO = -2
  ELSE IF (M .LT. 0) THEN
     INFO = -4
  ELSE IF (M .GT. LDX) THEN
     INFO = -4
  ELSE IF (N .LT. 0) THEN
     INFO = -5
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (M .EQ. 0) RETURN
  IF (N .EQ. 0) RETURN

  IF (M .EQ. LDX) THEN
     J = M * N
     CALL BIN_READ_1D(U, X, J, INFO)
  ELSE
     DO J = 1, N
        CALL BIN_READ_1D(U, X(1,J), M, INFO)
        IF (INFO .NE. 0) RETURN
     END DO
  END IF

END SUBROUTINE BIN_READ_2D

SUBROUTINE BIN_READ_0C(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  COMPLEX(RWP), INTENT(OUT) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  READ (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_READ_0C

SUBROUTINE BIN_READ_1C(U, X, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, N
  COMPLEX(RWP), INTENT(OUT) :: X(*)
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (N .LT. 0) THEN
     INFO = -3
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (N .EQ. 0) RETURN

  READ (UNIT=U, IOSTAT=INFO) X(1:N)

END SUBROUTINE BIN_READ_1C

SUBROUTINE BIN_READ_2C(U, LDX, X, M, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, LDX, M, N
  COMPLEX(RWP), INTENT(OUT) :: X(LDX,*)
  INTEGER, INTENT(OUT) :: INFO

  INTEGER :: J

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (LDX .LE. 0) THEN
     INFO = -2
  ELSE IF (M .LT. 0) THEN
     INFO = -4
  ELSE IF (M .GT. LDX) THEN
     INFO = -4
  ELSE IF (N .LT. 0) THEN
     INFO = -5
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (M .EQ. 0) RETURN
  IF (N .EQ. 0) RETURN

  IF (M .EQ. LDX) THEN
     J = M * N
     CALL BIN_READ_1C(U, X, J, INFO)
  ELSE
     DO J = 1, N
        CALL BIN_READ_1C(U, X(1,J), M, INFO)
        IF (INFO .NE. 0) RETURN
     END DO
  END IF

END SUBROUTINE BIN_READ_2C

SUBROUTINE BIN_READ_0Z(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  COMPLEX(DWP), INTENT(OUT) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  READ (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_READ_0Z

SUBROUTINE BIN_READ_1Z(U, X, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, N
  COMPLEX(DWP), INTENT(OUT) :: X(*)
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (N .LT. 0) THEN
     INFO = -3
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (N .EQ. 0) RETURN

  READ (UNIT=U, IOSTAT=INFO) X(1:N)

END SUBROUTINE BIN_READ_1Z

SUBROUTINE BIN_READ_2Z(U, LDX, X, M, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, LDX, M, N
  COMPLEX(DWP), INTENT(OUT) :: X(LDX,*)
  INTEGER, INTENT(OUT) :: INFO

  INTEGER :: J

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (LDX .LE. 0) THEN
     INFO = -2
  ELSE IF (M .LT. 0) THEN
     INFO = -4
  ELSE IF (M .GT. LDX) THEN
     INFO = -4
  ELSE IF (N .LT. 0) THEN
     INFO = -5
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (M .EQ. 0) RETURN
  IF (N .EQ. 0) RETURN

  IF (M .EQ. LDX) THEN
     J = M * N
     CALL BIN_READ_1Z(U, X, J, INFO)
  ELSE
     DO J = 1, N
        CALL BIN_READ_1Z(U, X(1,J), M, INFO)
        IF (INFO .NE. 0) RETURN
     END DO
  END IF

END SUBROUTINE BIN_READ_2Z

SUBROUTINE BIN_READ_0I(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  INTEGER, INTENT(OUT) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  READ (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_READ_0I

SUBROUTINE BIN_READ_1I(U, X, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, N
  INTEGER, INTENT(OUT) :: X(*)
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (N .LT. 0) THEN
     INFO = -3
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (N .EQ. 0) RETURN

  READ (UNIT=U, IOSTAT=INFO) X(1:N)

END SUBROUTINE BIN_READ_1I

SUBROUTINE BIN_READ_2I(U, LDX, X, M, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, LDX, M, N
  INTEGER, INTENT(OUT) :: X(LDX,*)
  INTEGER, INTENT(OUT) :: INFO

  INTEGER :: J

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (LDX .LE. 0) THEN
     INFO = -2
  ELSE IF (M .LT. 0) THEN
     INFO = -4
  ELSE IF (M .GT. LDX) THEN
     INFO = -4
  ELSE IF (N .LT. 0) THEN
     INFO = -5
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (M .EQ. 0) RETURN
  IF (N .EQ. 0) RETURN

  IF (M .EQ. LDX) THEN
     J = M * N
     CALL BIN_READ_1I(U, X, J, INFO)
  ELSE
     DO J = 1, N
        CALL BIN_READ_1I(U, X(1,J), M, INFO)
        IF (INFO .NE. 0) RETURN
     END DO
  END IF

END SUBROUTINE BIN_READ_2I

SUBROUTINE BIN_READ_0L(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  LOGICAL, INTENT(OUT) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  READ (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_READ_0L

SUBROUTINE BIN_READ_1L(U, X, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, N
  LOGICAL, INTENT(OUT) :: X(*)
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (N .LT. 0) THEN
     INFO = -3
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (N .EQ. 0) RETURN

  READ (UNIT=U, IOSTAT=INFO) X(1:N)

END SUBROUTINE BIN_READ_1L

SUBROUTINE BIN_READ_2L(U, LDX, X, M, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, LDX, M, N
  LOGICAL, INTENT(OUT) :: X(LDX,*)
  INTEGER, INTENT(OUT) :: INFO

  INTEGER :: J

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (LDX .LE. 0) THEN
     INFO = -2
  ELSE IF (M .LT. 0) THEN
     INFO = -4
  ELSE IF (M .GT. LDX) THEN
     INFO = -4
  ELSE IF (N .LT. 0) THEN
     INFO = -5
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (M .EQ. 0) RETURN
  IF (N .EQ. 0) RETURN

  IF (M .EQ. LDX) THEN
     J = M * N
     CALL BIN_READ_1L(U, X, J, INFO)
  ELSE
     DO J = 1, N
        CALL BIN_READ_1L(U, X(1,J), M, INFO)
        IF (INFO .NE. 0) RETURN
     END DO
  END IF

END SUBROUTINE BIN_READ_2L

SUBROUTINE BIN_WRITE_0A(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  CHARACTER(LEN=*), INTENT(IN) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  WRITE (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_WRITE_0A

SUBROUTINE BIN_WRITE_0S(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  REAL(RWP), INTENT(IN) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  WRITE (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_WRITE_0S

SUBROUTINE BIN_WRITE_1S(U, X, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, N
  REAL(RWP), INTENT(IN) :: X(*)
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (N .LT. 0) THEN
     INFO = -3
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (N .EQ. 0) RETURN

  WRITE (UNIT=U, IOSTAT=INFO) X(1:N)

END SUBROUTINE BIN_WRITE_1S

SUBROUTINE BIN_WRITE_2S(U, LDX, X, M, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, LDX, M, N
  REAL(RWP), INTENT(IN) :: X(LDX,*)
  INTEGER, INTENT(OUT) :: INFO

  INTEGER :: J

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (LDX .LE. 0) THEN
     INFO = -2
  ELSE IF (M .LT. 0) THEN
     INFO = -4
  ELSE IF (M .GT. LDX) THEN
     INFO = -4
  ELSE IF (N .LT. 0) THEN
     INFO = -5
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (M .EQ. 0) RETURN
  IF (N .EQ. 0) RETURN

  IF (M .EQ. LDX) THEN
     J = M * N
     CALL BIN_WRITE_1S(U, X, J, INFO)
  ELSE
     DO J = 1, N
        CALL BIN_WRITE_1S(U, X(1,J), M, INFO)
        IF (INFO .NE. 0) RETURN
     END DO
  END IF

END SUBROUTINE BIN_WRITE_2S

SUBROUTINE BIN_WRITE_0D(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  REAL(DWP), INTENT(IN) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  WRITE (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_WRITE_0D

SUBROUTINE BIN_WRITE_1D(U, X, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, N
  REAL(DWP), INTENT(IN) :: X(*)
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (N .LT. 0) THEN
     INFO = -3
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (N .EQ. 0) RETURN

  WRITE (UNIT=U, IOSTAT=INFO) X(1:N)

END SUBROUTINE BIN_WRITE_1D

SUBROUTINE BIN_WRITE_2D(U, LDX, X, M, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, LDX, M, N
  REAL(DWP), INTENT(IN) :: X(LDX,*)
  INTEGER, INTENT(OUT) :: INFO

  INTEGER :: J

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (LDX .LE. 0) THEN
     INFO = -2
  ELSE IF (M .LT. 0) THEN
     INFO = -4
  ELSE IF (M .GT. LDX) THEN
     INFO = -4
  ELSE IF (N .LT. 0) THEN
     INFO = -5
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (M .EQ. 0) RETURN
  IF (N .EQ. 0) RETURN

  IF (M .EQ. LDX) THEN
     J = M * N
     CALL BIN_WRITE_1D(U, X, J, INFO)
  ELSE
     DO J = 1, N
        CALL BIN_WRITE_1D(U, X(1,J), M, INFO)
        IF (INFO .NE. 0) RETURN
     END DO
  END IF

END SUBROUTINE BIN_WRITE_2D

SUBROUTINE BIN_WRITE_0C(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  COMPLEX(RWP), INTENT(IN) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  WRITE (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_WRITE_0C

SUBROUTINE BIN_WRITE_1C(U, X, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, N
  COMPLEX(RWP), INTENT(IN) :: X(*)
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (N .LT. 0) THEN
     INFO = -3
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (N .EQ. 0) RETURN

  WRITE (UNIT=U, IOSTAT=INFO) X(1:N)

END SUBROUTINE BIN_WRITE_1C

SUBROUTINE BIN_WRITE_2C(U, LDX, X, M, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, LDX, M, N
  COMPLEX(RWP), INTENT(IN) :: X(LDX,*)
  INTEGER, INTENT(OUT) :: INFO

  INTEGER :: J

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (LDX .LE. 0) THEN
     INFO = -2
  ELSE IF (M .LT. 0) THEN
     INFO = -4
  ELSE IF (M .GT. LDX) THEN
     INFO = -4
  ELSE IF (N .LT. 0) THEN
     INFO = -5
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (M .EQ. 0) RETURN
  IF (N .EQ. 0) RETURN

  IF (M .EQ. LDX) THEN
     J = M * N
     CALL BIN_WRITE_1C(U, X, J, INFO)
  ELSE
     DO J = 1, N
        CALL BIN_WRITE_1C(U, X(1,J), M, INFO)
        IF (INFO .NE. 0) RETURN
     END DO
  END IF

END SUBROUTINE BIN_WRITE_2C

SUBROUTINE BIN_WRITE_0Z(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  COMPLEX(DWP), INTENT(IN) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  WRITE (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_WRITE_0Z

SUBROUTINE BIN_WRITE_1Z(U, X, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, N
  COMPLEX(DWP), INTENT(IN) :: X(*)
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (N .LT. 0) THEN
     INFO = -3
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (N .EQ. 0) RETURN

  WRITE (UNIT=U, IOSTAT=INFO) X(1:N)

END SUBROUTINE BIN_WRITE_1Z

SUBROUTINE BIN_WRITE_2Z(U, LDX, X, M, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, LDX, M, N
  COMPLEX(DWP), INTENT(IN) :: X(LDX,*)
  INTEGER, INTENT(OUT) :: INFO

  INTEGER :: J

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (LDX .LE. 0) THEN
     INFO = -2
  ELSE IF (M .LT. 0) THEN
     INFO = -4
  ELSE IF (M .GT. LDX) THEN
     INFO = -4
  ELSE IF (N .LT. 0) THEN
     INFO = -5
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (M .EQ. 0) RETURN
  IF (N .EQ. 0) RETURN

  IF (M .EQ. LDX) THEN
     J = M * N
     CALL BIN_WRITE_1Z(U, X, J, INFO)
  ELSE
     DO J = 1, N
        CALL BIN_WRITE_1Z(U, X(1,J), M, INFO)
        IF (INFO .NE. 0) RETURN
     END DO
  END IF

END SUBROUTINE BIN_WRITE_2Z

SUBROUTINE BIN_WRITE_0I(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  INTEGER, INTENT(IN) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  WRITE (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_WRITE_0I

SUBROUTINE BIN_WRITE_1I(U, X, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, N
  INTEGER, INTENT(IN) :: X(*)
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (N .LT. 0) THEN
     INFO = -3
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (N .EQ. 0) RETURN

  WRITE (UNIT=U, IOSTAT=INFO) X(1:N)

END SUBROUTINE BIN_WRITE_1I

SUBROUTINE BIN_WRITE_2I(U, LDX, X, M, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, LDX, M, N
  INTEGER, INTENT(IN) :: X(LDX,*)
  INTEGER, INTENT(OUT) :: INFO

  INTEGER :: J

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (LDX .LE. 0) THEN
     INFO = -2
  ELSE IF (M .LT. 0) THEN
     INFO = -4
  ELSE IF (M .GT. LDX) THEN
     INFO = -4
  ELSE IF (N .LT. 0) THEN
     INFO = -5
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (M .EQ. 0) RETURN
  IF (N .EQ. 0) RETURN

  IF (M .EQ. LDX) THEN
     J = M * N
     CALL BIN_WRITE_1I(U, X, J, INFO)
  ELSE
     DO J = 1, N
        CALL BIN_WRITE_1I(U, X(1,J), M, INFO)
        IF (INFO .NE. 0) RETURN
     END DO
  END IF

END SUBROUTINE BIN_WRITE_2I

SUBROUTINE BIN_WRITE_0L(U, X, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U
  LOGICAL, INTENT(IN) :: X
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN

  WRITE (UNIT=U, IOSTAT=INFO) X

END SUBROUTINE BIN_WRITE_0L

SUBROUTINE BIN_WRITE_1L(U, X, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, N
  LOGICAL, INTENT(IN) :: X(*)
  INTEGER, INTENT(OUT) :: INFO

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (N .LT. 0) THEN
     INFO = -3
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (N .EQ. 0) RETURN

  WRITE (UNIT=U, IOSTAT=INFO) X(1:N)

END SUBROUTINE BIN_WRITE_1L

SUBROUTINE BIN_WRITE_2L(U, LDX, X, M, N, INFO)

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: U, LDX, M, N
  LOGICAL, INTENT(IN) :: X(LDX,*)
  INTEGER, INTENT(OUT) :: INFO

  INTEGER :: J

  IF (U .LT. 0) THEN
     INFO = -1
  ELSE IF (LDX .LE. 0) THEN
     INFO = -2
  ELSE IF (M .LT. 0) THEN
     INFO = -4
  ELSE IF (M .GT. LDX) THEN
     INFO = -4
  ELSE IF (N .LT. 0) THEN
     INFO = -5
  ELSE
     INFO = 0
  END IF

  IF (INFO .NE. 0) RETURN
  IF (M .EQ. 0) RETURN
  IF (N .EQ. 0) RETURN

  IF (M .EQ. LDX) THEN
     J = M * N
     CALL BIN_WRITE_1L(U, X, J, INFO)
  ELSE
     DO J = 1, N
        CALL BIN_WRITE_1L(U, X(1,J), M, INFO)
        IF (INFO .NE. 0) RETURN
     END DO
  END IF

END SUBROUTINE BIN_WRITE_2L
