REAL(RWP), PARAMETER :: S_ZERO =  0.0_RWP
REAL(RWP), PARAMETER :: S_ONE  =  1.0_RWP
REAL(RWP), PARAMETER :: S_MONE = -1.0_RWP
REAL(RWP), PARAMETER :: S_TWO  =  2.0_RWP
REAL(RWP), PARAMETER :: S_HALF =  0.5_RWP

REAL(DWP), PARAMETER :: D_ZERO =  0.0_DWP
REAL(DWP), PARAMETER :: D_ONE  =  1.0_DWP
REAL(DWP), PARAMETER :: D_MONE = -1.0_DWP
REAL(DWP), PARAMETER :: D_TWO  =  2.0_DWP
REAL(DWP), PARAMETER :: D_MTWO = -2.0_DWP
REAL(DWP), PARAMETER :: D_HALF =  0.5_DWP

COMPLEX(RWP), PARAMETER :: C_ZERO  = (S_ZERO,S_ZERO)
COMPLEX(RWP), PARAMETER :: C_ONE   = ( S_ONE,S_ZERO)
COMPLEX(RWP), PARAMETER :: C_MONE  = (S_MONE,S_ZERO)

COMPLEX(DWP), PARAMETER :: Z_ZERO  = (D_ZERO,D_ZERO)
COMPLEX(DWP), PARAMETER :: Z_ONE   = ( D_ONE,D_ZERO)
COMPLEX(DWP), PARAMETER :: Z_MONE  = (D_MONE,D_ZERO)
