#ifndef NO_FMA
PURE FUNCTION SFMA(A, B, C)
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE
  REAL(c_float), INTENT(IN) :: A, B, C
  REAL(c_float) :: SFMA
  !DIR$ FMA
  SFMA = A * B + C
END FUNCTION SFMA
PURE FUNCTION DFMA(A, B, C)
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE
  REAL(c_double), INTENT(IN) :: A, B, C
  REAL(c_double) :: DFMA
  !DIR$ FMA
  DFMA = A * B + C
END FUNCTION DFMA
#endif

#ifndef USE_INTEL
ELEMENTAL FUNCTION SRSQRT(X)
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE
  REAL(c_float), INTENT(IN) :: X
  REAL(c_float) :: SRSQRT
  SRSQRT = S_ONE / SQRT(X)
END FUNCTION SRSQRT
ELEMENTAL FUNCTION DRSQRT(X)
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE
  REAL(c_double), INTENT(IN) :: X
  REAL(c_double) :: DRSQRT
  DRSQRT = D_ONE / SQRT(X)
END FUNCTION DRSQRT
PURE SUBROUTINE SSINCOS(X, S, C)
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE
  REAL(c_float), INTENT(IN), VALUE :: X
  REAL(c_float), INTENT(OUT) :: S, C
  S = SIN(X)
  C = COS(X)
END SUBROUTINE SSINCOS
#endif

#ifdef USE_GNU
PURE SUBROUTINE DSINCOS(X, S, C)
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE
  REAL(c_double), INTENT(IN), VALUE :: X
  REAL(c_double), INTENT(OUT) :: S, C
  S = SIN(X)
  C = COS(X)
END SUBROUTINE DSINCOS
#endif
