MODULE VN_ALLOC_F
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE

  INTERFACE
     FUNCTION VN_ALLOC(M, N, SZT, LDA, ACT) BIND(C,NAME='vn_alloc2')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       INTEGER, VALUE, INTENT(IN) :: M, N, ACT
       INTEGER(KIND=c_size_t), VALUE, INTENT(IN) :: SZT
       INTEGER, INTENT(OUT) :: LDA
       TYPE(c_ptr) :: VN_ALLOC
     END FUNCTION VN_ALLOC
  END INTERFACE

  INTERFACE
     SUBROUTINE VN_FREE(PTR) BIND(C,NAME='vn_free')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       TYPE(c_ptr), VALUE, INTENT(IN) :: PTR
     END SUBROUTINE VN_FREE
  END INTERFACE

  INTERFACE
     SUBROUTINE VN_FREEP(PTR) BIND(C,NAME='vn_freep')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(INOUT) :: PTR
     END SUBROUTINE VN_FREEP
  END INTERFACE

CONTAINS
END MODULE VN_ALLOC_F
