MODULE VN_SORT_F
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE

  INTERFACE
     FUNCTION VN_BSEARCH(X, A, N, SZ, CMP) BIND(C,NAME='bsearch')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(IN), VALUE :: X, A
       INTEGER(c_size_t), INTENT(IN), VALUE :: N, SZ
       TYPE(c_funptr), INTENT(IN), VALUE :: CMP
       TYPE(c_ptr) :: VN_BSEARCH
     END FUNCTION VN_BSEARCH
  END INTERFACE

  INTERFACE
     SUBROUTINE VN_QSORT(A, N, SZ, CMP) BIND(C,NAME='qsort')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(IN), VALUE :: A
       INTEGER(c_size_t), INTENT(IN), VALUE :: N, SZ
       TYPE(c_funptr), INTENT(IN), VALUE :: CMP
     END SUBROUTINE VN_QSORT
  END INTERFACE

  ABSTRACT INTERFACE
     FUNCTION VN_QSORT_CMP(PA, PB)
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       INTEGER(c_intptr_t), INTENT(IN), VALUE :: PA, PB
       INTEGER(c_int) :: VN_QSORT_CMP
     END FUNCTION VN_QSORT_CMP
  END INTERFACE

CONTAINS
END MODULE VN_SORT_F
