MODULE VN_SORT_F
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE

  INTERFACE
     RECURSIVE FUNCTION VN_BSEARCH(X, A, N, SZ, CMP) BIND(C,NAME='bsearch')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(IN), VALUE :: X, A
       INTEGER(KIND=c_size_t), INTENT(IN), VALUE :: N, SZ
       TYPE(c_funptr), INTENT(IN), VALUE :: CMP
       TYPE(c_ptr) :: VN_BSEARCH
     END FUNCTION VN_BSEARCH
  END INTERFACE

#ifdef _GNU_SOURCE
  INTERFACE
     RECURSIVE SUBROUTINE VN_QSORT(A, N, SZ, CMP, CTX) BIND(C,NAME='qsort_r')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(IN), VALUE :: A, CTX
       INTEGER(KIND=c_size_t), INTENT(IN), VALUE :: N, SZ
       TYPE(c_funptr), INTENT(IN), VALUE :: CMP
     END SUBROUTINE VN_QSORT
  END INTERFACE

  ABSTRACT INTERFACE
     RECURSIVE FUNCTION VN_QSORT_CMP(PA, PB, CTX) BIND(C)
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(IN), VALUE :: PA, PB, CTX
       INTEGER(KIND=c_int) :: VN_QSORT_CMP
     END FUNCTION VN_QSORT_CMP
  END INTERFACE
#else
  INTERFACE
     RECURSIVE SUBROUTINE VN_QSORT(A, N, SZ, CTX, CMP) BIND(C,NAME='qsort_r')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(IN), VALUE :: A, CTX
       INTEGER(KIND=c_size_t), INTENT(IN), VALUE :: N, SZ
       TYPE(c_funptr), INTENT(IN), VALUE :: CMP
     END SUBROUTINE VN_QSORT
  END INTERFACE

  ABSTRACT INTERFACE
     RECURSIVE FUNCTION VN_QSORT_CMP(CTX, PA, PB) BIND(C)
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(IN), VALUE :: CTX, PA, PB
       INTEGER(KIND=c_int) :: VN_QSORT_CMP
     END FUNCTION VN_QSORT_CMP
  END INTERFACE
#endif

CONTAINS
END MODULE VN_SORT_F
