MODULE VN_SORT_F
  IMPLICIT NONE

  INTERFACE
     RECURSIVE FUNCTION VN_BSEARCH(X, A, N, SZ, CMP) BIND(C,NAME='bsearch')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_funptr, c_ptr, c_size_t
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(IN), VALUE :: X, A
       INTEGER(KIND=c_size_t), INTENT(IN), VALUE :: N, SZ
       TYPE(c_funptr), INTENT(IN), VALUE :: CMP
       TYPE(c_ptr) :: VN_BSEARCH
     END FUNCTION VN_BSEARCH
  END INTERFACE

  INTERFACE
     RECURSIVE SUBROUTINE VN_QSORT(A, N, SZ, CMP) BIND(C,NAME='qsort')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_funptr, c_ptr, c_size_t
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(IN), VALUE :: A
       INTEGER(KIND=c_size_t), INTENT(IN), VALUE :: N, SZ
       TYPE(c_funptr), INTENT(IN), VALUE :: CMP
     END SUBROUTINE VN_QSORT
  END INTERFACE

  ABSTRACT INTERFACE
     RECURSIVE FUNCTION VN_QSORT_CMP(PA, PB) BIND(C)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_ptr, c_int
       IMPLICIT NONE
       TYPE(c_ptr), INTENT(IN), VALUE :: PA, PB
       INTEGER(KIND=c_int) :: VN_QSORT_CMP
     END FUNCTION VN_QSORT_CMP
  END INTERFACE

CONTAINS
END MODULE VN_SORT_F
