MODULE VN_TIMER_F
  USE, INTRINSIC :: ISO_C_BINDING
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64
  IMPLICIT NONE

  REAL, PARAMETER :: SUS2S = 1E-6
  REAL, PARAMETER :: SNS2S = 1E-9

  DOUBLE PRECISION, PARAMETER :: DUS2S = 1D-6
  DOUBLE PRECISION, PARAMETER :: DNS2S = 1D-9

  INTERFACE
     FUNCTION VN_GET_THREAD_NS() BIND(C,NAME='vn_get_thread_ns')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64
       IMPLICIT NONE
       INTEGER(KIND=INT64) :: VN_GET_THREAD_NS
     END FUNCTION VN_GET_THREAD_NS
  END INTERFACE

  INTERFACE
     FUNCTION VN_GET_SYS_US() BIND(C,NAME='vn_get_sys_us')
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT64
       IMPLICIT NONE
       INTEGER(KIND=INT64) :: VN_GET_SYS_US
     END FUNCTION VN_GET_SYS_US
  END INTERFACE

  INTERFACE
     FUNCTION RDTSC_BEG(AUX) BIND(C,NAME='rdtsc_beg_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int32_t, c_int64_t
       IMPLICIT NONE
       INTEGER(KIND=c_int32_t), INTENT(OUT), TARGET :: AUX
       INTEGER(KIND=c_int64_t) :: RDTSC_BEG
     END FUNCTION RDTSC_BEG
  END INTERFACE

  INTERFACE
     FUNCTION RDTSC_END(AUX) BIND(C,NAME='rdtsc_end_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int32_t, c_int64_t
       IMPLICIT NONE
       INTEGER(KIND=c_int32_t), INTENT(OUT), TARGET :: AUX
       INTEGER(KIND=c_int64_t) :: RDTSC_END
     END FUNCTION RDTSC_END
  END INTERFACE

  INTERFACE
     FUNCTION TSC_GET_FREQ_HZ(REM) BIND(C,NAME='tsc_get_freq_hz_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int64_t
       IMPLICIT NONE
       INTEGER(KIND=c_int64_t), INTENT(OUT), TARGET :: REM
       INTEGER(KIND=c_int64_t) :: TSC_GET_FREQ_HZ
     END FUNCTION TSC_GET_FREQ_HZ
  END INTERFACE

  INTERFACE
     FUNCTION TSC_LAP(F, B, E, S, R) BIND(C,NAME='tsc_lap_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_int64_t, c_double
       IMPLICIT NONE
       INTEGER(KIND=c_int64_t), INTENT(IN), VALUE :: F, B, E
       INTEGER(KIND=c_int64_t), INTENT(OUT), TARGET :: S, R
       REAL(KIND=c_double) :: TSC_LAP
     END FUNCTION TSC_LAP
  END INTERFACE

CONTAINS
END MODULE VN_TIMER_F
