MODULE VN_TIMER_F
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE

  REAL, PARAMETER :: SUS2S = 1E-6
  REAL, PARAMETER :: SNS2S = 1E-9

  DOUBLE PRECISION, PARAMETER :: DUS2S = 1D-6
  DOUBLE PRECISION, PARAMETER :: DNS2S = 1D-9

  INTERFACE
     FUNCTION VN_GET_THREAD_NS() BIND(C,NAME='vn_get_thread_ns')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       INTEGER(KIND=8) :: VN_GET_THREAD_NS
     END FUNCTION VN_GET_THREAD_NS
  END INTERFACE

  INTERFACE
     FUNCTION VN_GET_SYS_US() BIND(C,NAME='vn_get_sys_us')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       INTEGER(KIND=8) :: VN_GET_SYS_US
     END FUNCTION VN_GET_SYS_US
  END INTERFACE

CONTAINS
END MODULE VN_TIMER_F
