MODULE VN_TIMER_F
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE

  INTERFACE
     FUNCTION VN_GET_THREAD_NS() BIND(C,NAME='vn_get_thread_ns')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       INTEGER(KIND=8) :: VN_GET_THREAD_NS
     END FUNCTION VN_GET_THREAD_NS
  END INTERFACE

  INTERFACE
     FUNCTION VN_GET_SYS_US() BIND(C,NAME='vn_get_sys_us')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       INTEGER(KIND=8) :: VN_GET_SYS_US
     END FUNCTION VN_GET_SYS_US
  END INTERFACE

CONTAINS
END MODULE VN_TIMER_F
